### ISSUE TITLE
We need an Admininistration Interface

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#100]
We currently have no “admin” functionality. We need some way to:
 * See (and edit!) our users
 * See and edit (and upload) videos (see also next points)
 * Organize content
 * Users and roles
 
Proposal: We cannot really do without this. It is for internal use, so we can try and find a quick-and-dirty solution based on something like https://atmospherejs.com/houston/admin.

**Comment by jellegerbrandy** [comment]
We have been studying alternatives. There is a list here: http://mongodb-tools.com/. Our shortlist at this moment is:

 1. Roll-your-own: probably out of scope as too much work (i.e. weeks)
 2. http://www.drmongo.com/
 3. https://www.nosqlclient.com/demo/

There are also non-free solutions that may be of use.

Some specs:
 * we need to be able to do basic CRUD operations on all records
 * we want to have some precalculate queries that give statistics
 * we don't care much about graphics or even usability, as this will be for internal use

**Comment by eliawk** [comment]
i've already installed dr.mongo on my local machine and it seems very good. the only limit it is quite raw in the edit mode (you to fight with some json) 
![screenshot 2017-09-13 10 26 39](https://user-images.githubusercontent.com/362016/30367328-414e22e0-986e-11e7-98b2-5a65cda87a35.png)

but i think create a custom admin with some decent UI it's too time expensive.

**Comment by jellegerbrandy** [comment]
Now that we decided to have the blcokchain as the "source of truth" of our date, editing data is not the most important point here. 

I say go for dr. mongo.

**Comment by jellegerbrandy** [comment]
elia, plz document here: https://github.com/Paratii-Video/devops/blob/master/docs/drmongo.md

**Comment by jellegerbrandy** [comment]
so the micro gives out-of-memory erros. Here's a new medium instance to installd rmongo on (and we will mvoe the playerthere too): 52.37.8.77

**Comment by jellegerbrandy** [comment]
https://drmongo.paratii.video
