### ISSUE TITLE
Experiment with and test embedding

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#101]
We need to have a more precise idea about the limits of embedding our player in 3rd party websites. 

Useful would be:

- Have some sample webpages with our player embedded
- Have a precise idea about browser/iframe limitations
- Document how 3rd party websites like Facebook and others may limit embeddability 
- Document precisely in the README how to embed our player

**Comment by jellegerbrandy** [comment]
Some thoughts about this:

**Goal:** The player needs to be embeddable (like the youtube player)
**Status:** Not tested yet.
**Proposal:** Do some experimenting on the short term to see what issues we encounter.

**Possible issues:**
Interaction between multiple embedded players on the same page.
Browser compatibility. 

**What goes where: _embeddable player vs website_**
Having an “embeddable player” brings with it a number of constraints: it needs to be as lightweight as possible; needs to be usable also on very small spaces (in my facebook feed youtube 476 x 260 pixels); sharing sites may put limits on embeddability of 3rd party content that we may want to avoid. 
Where we want to arrive at it a situation where an embeddable player has minimal functionality, and a user is redirected to dedicated larger site that is not subject to these limits, making use of the larger “real estate” for improved discroverability and more “complex” UX (such as access to statistics, uploading an organizing content, transaction history, etc). It is pretty much what Youtube already does.


**User flow Proposal:** 
The embeddable player plays video, is an ipfs node, is a wallet. Typically accessed with a video link. For more sophisticated content discovery, for uploading or organizing stuff, anything with a more complex UI, the user is referred to the dedicated site. 
With a bit of smart programming, this does not need to be much extra work, as both versions (player and site) can use the same code base.

**Comment by felipegaucho** [comment]
Closing this in favour of #116, which contains stuff that's missing from this issue.
