### ISSUE TITLE
Document embed sizes/versions (i.e. Mini Mode & Tiny Mode)

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#116]
Here's a proposal - to discuss:

For the MVP, we have two versions (two views) of the player:

1. One "full screen" standalone versions with all functionality 
2. One "embeddable" version whose main function is to play a video, and that has minimal functionality

Here "minimal functionality" means the following:

   1. Plays video 
   2. Is an IPFS node
   3. Creates/reads existing wallet (cf. #105)
   4. Existing users can log in
   5. reduced user interaction (like/dislike, sharing)
   6. A link to the "full screen" version

The reason to limit the functionlity in the small, embeddable, version are (1) we have simply less "real estate", less space for the UX, and user expections for UX in an iframe are different and (2) optmiziation is more important for embeddabilty, and less functionality = easier optimization

More complex (in the sense of "more complex UI") functionality is done in the "full screen" function, and includes:
   1. All data entry stuff (create an account, tagging videos)
   2. All discoverability that is not absolutely basic (search, channels, etc - the minimal version will just suggest new videos after you finished watching yours)
   3. Wallet recoverability
   4. Transaction history
   5. Sending ETH, PTI explicitly

**Comment by ya7ya** [comment]
IMO , I think embeddable version is important for the MVP since creators would probably wanna embed the video in their existing platforms. and we need the publicity 😄 

and the fact that we have limited time means we gotta create the smallest possible implementation then gradually add functionalities , so embeddable player + uploader , then we can add functions from there.

**Comment by felipegaucho** [comment]
After some research/pondering, we believe an ideal scenario contemplates the following sizes/versions:

**1** ✦ **Smallest mode** (e.g. 160 x 120) is activated when the iFrame is < 260 px wide. It's an static image that shows title + play + backimage - and is itself a direct link to fullscreen.
**2** ✦ **Micro mode** (e.g. 260 x 190) is activated when the iFrame is > 260 px wide. It's an static image that shows title + play + backimage + **duration + price** - and is itself a direct link to fullscreen.
**3** ✦ **Tiny mode** (e.g. 340 x 190) is activated when the iframe is > 340 px wide. It's the "minimum playable version". It shows title + play + backimage + duration + views + ratings + link to fullscreen (+ price, if there is + further screens for login + PPV confirmation) + **the video.**
**4** ✦ **Mini mode** (e.g. 490X280) is activated when the iframe is > 490 px wide. It shows title + play + backimage + duration + views + ratings + link to fullscreen (+ price, if there is) + login + "share" (and copy link to clipboard) + "watch later" + the video + **menu and associated screens.**
**5** ✦ **Mobile Horizontal Fullscreen Mode** (depends on the size of your mobile screen) is activated when the user taps the fullscreen button and holds the device in horizontal position. It has all the features of the _Mini Mode_.
**6** ✦ **Mobile Vertical Fullscreen Mode** (depends on the size of your mobile screen) is activated when the user tap the fullscreen button and holds the device in vertical position. It shows all the features of the _Mini Mode / Mobile Horizontal Fullscreen Mode_, but optimized for vertical [Like in here (rough)](https://github.com/Paratii-Video/paratii-player/files/1308194/FULL_MOBILE_VERT.pdf).
**7** ✦ **Large mode** (e.g. 1920 x 1080). A fullscreen standalone version **_(there must have an activation threshold here, right?_**).

For now, we've produced a proposal for Tiny. It's undergoing some changes still (like lack of volume control in screen 10). See the image below:

**[TINY.pdf](https://github.com/Paratii-Video/paratii-player/files/1308170/TINY.pdf)**

**For the MVP we think we need tiny mode + mini mode + smallest** (this last one is minimal and static). _Mobile Vertical Fullscreen, Mobile Horizontal Fullscreen, Micro_ and _Large_ modes can come afterwards. _Tiny_ will most likely appear in mobile, where its fullscreen link will bring to _Mini_, which will also be nice on desktops, but won't have a link for "further fullscreen" (on desktop) yet. So we'll implement the front-end for these (_Tiny + Mini_), beginning w/ the pay-per-view flow.

To have an idea for the _Mobile Horizontal Fullscreen Mode_, similar to the _Mini Mode_ (very rough still), see this WIP: [flow mobile_HORIZONTAL.pdf](https://github.com/Paratii-Video/paratii-player/files/1308195/flow.mobile_HORIZONTAL.pdf)

Let us know what you think.

**Comment by jellegerbrandy** [comment]
This is a great start.  Just a remark on the signin flow:

- the signin/signup flow in our case is complicated by the fact that the keystore (i.e. the data-file that is used  to sign transactions) is stored locally in your browser. in practice, this means that if you log in from a new device, you need to give not only your password, but also the 12-word keyphrase that is needed to regenerate your wallet. I'll try to document this more precisely.

**Comment by felipegaucho** [comment]
Still missing:

- [x] **Document precisely in the README** how to embed our player; its preset sizes (the above must be checked w/ @pedrocasa); and their respective features.
- [x] Document how 3rd party websites like Facebook and others may limit embeddability (lots of inputs from our previous discussions).
- [ ] Document the issue as for _logging in from a new device -> requires not only your password, but also the keyphrase to regenerate wallet._

**Comment by geckoslair** [comment]
just the mini version for October sprint #143

**Comment by geckoslair** [comment]
@pedrocasa @felipegaucho @jellegerbrandy 
can we have a progress of this task? I've publish the documentation in the related repo:

https://github.com/Paratii-Video/paratii-embed

still missing something?

**Comment by jellegerbrandy** [comment]
i'm closing this issue as it is all over the place :-)
I made a wiki page to document the breakpoints. It is here: https://github.com/Paratii-Video/paratii-player/wiki/Breakpoints
