### ISSUE TITLE
show "connecting to blockchain..." instead of "you have no ether"

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#127]

**Comment by mrocha94** [comment]
@jellegerbrandy does this [commit](https://github.com/Paratii-Video/paratii-player/commit/7d91655ddd5592de709200e654852c2913ac5bc6) resolve?

**Comment by jellegerbrandy** [comment]
I think so, yes, that this would work, very good.

Just to be pedeantic: it is probably cleaner to use to `Session.get('eth_isConnected')`. (which is set in `updateSession`, which is hte function we call when pining the blockchain for new info). So, the `eth_balance` code would first check for this var, and if it is false, return 'Not connected to the blockchain" (or "connecting..."), and when true, proceeds with checking the balance.

**Comment by mrocha94** [comment]
So, it has these states:
* Not connected: "Not connected to the blockchain"
* Connected:
  * getting balance: "Connecting to blockchain"
  * empty wallet: "You don't own Ether"
  * amount: "You own {{amount}} Ether"

**Comment by jellegerbrandy** [comment]
yes. For the moment though we do not distinguish "connecting" from "not
connected" (if we are not connected we will continue trying)

On Oct 9, 2017 19:44, "Mateus Rocha Mazzari" <notifications@github.com>
wrote:

So, it has these states:

   - Not connected: "Not connected to the blockchain"
   - Connected:
      - getting balance: "Connecting to blockchain"
      - empty wallet: "You don't own Ether"
      - amount: "You own {{amount}} Ether"

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Paratii-Video/paratii-player/issues/127#issuecomment-335230608>,
or mute the thread
