### ISSUE TITLE
Player Buttons/information

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-player#141]
One of the tricky parts that I and @jrgarou are dealing with right now are the definitions of buttons and all the information that we need to show in the play bar.

It's important to think about what a user needs while watching a medium-large duration video and which problems he could find in the watching process.

For the mini version, we designed a clean one, with only the timeline, pause button, skip the video, duration and the popup that previews the video as you glide over the timeline.... but we are not sure, @jrgarou  specially, if that is the right decision and we'd like to know what the rest of the team thinks about it

Is this enough information on the main screen? Do we need anything else? Should we add more icons/other features? Let me know what you think

(image below)

![capture-2](https://user-images.githubusercontent.com/30123644/31407748-66ca868e-addc-11e7-9e1e-b5ffa7e664e2.PNG)
![capture](https://user-images.githubusercontent.com/30123644/31407750-66e8c1e4-addc-11e7-87a6-15269a79ae27.PNG)
![capture-3](https://user-images.githubusercontent.com/30123644/31408027-78a48868-addd-11e7-8002-18d768bcd8ed.PNG)

**Comment by pedrocasa** [comment]
Some examples of other play sliders,

![vimeo](https://user-images.githubusercontent.com/30123644/31407769-7d28ad66-addc-11e7-9d72-9918ce4a84b3.png)
![windowsdefault](https://user-images.githubusercontent.com/30123644/31407770-7d47d0ce-addc-11e7-85d3-dbd175bea22e.png)
![youtube](https://user-images.githubusercontent.com/30123644/31407771-7d66f71a-addc-11e7-94b1-465aa1840bf8.png)
![instagram](https://user-images.githubusercontent.com/30123644/31407772-7d966a0e-addc-11e7-8e48-ae4897ea06d7.png)
![jw](https://user-images.githubusercontent.com/30123644/31407773-7db528c2-addc-11e7-8d34-8819600dddb2.png)
![netflix](https://user-images.githubusercontent.com/30123644/31407774-7dcfcbbe-addc-11e7-99a3-9ff114956521.png)

**Comment by felipegaucho** [comment]
Very clean and beautiful @pedrocasa 
@ya7ya how burdenous in terms of bandwidth is to have a small thumbnail preview when hovering over the progress bar (towards the end, which you haven't received yet)? Maybe best would be to avoid it for now?
Also, we need a better placeholder =)

**Comment by ya7ya** [comment]
@felipegaucho it's no problem if you wanna include few pictures as thumbnail , this happens during the transcoding process, creating a short clip might be a little trickier though . I'll look into it :+1:

**Comment by jrgarou** [comment]
@pedrocasa I think the **mute button** is a important featured to the user

**Comment by jellegerbrandy** [comment]
I think that "as minimal as possible" is a good approach at this point. We must not think of this as the final design, but as a first iteration. We can add more functinoality later if we find that our users need/want it.

Wrt the thumbnail preview: our player will probably be slower to load than other players out there, because we have to set up the ipfs connections. One idea is to show some text animation in which we explain what paratii is, what the user is waiting for, etc. (A bit like what some software installers do when you have to wait). If this is text only, it can be very low bandwidth. What do you think?

**Comment by pedrocasa** [comment]
@jellegerbrandy  just on the first time or every time it appears embedded on a website?

**Comment by jellegerbrandy** [comment]
I moved the discussion about showing texts on load to a new issue #154
