### ISSUE TITLE
define and upload demoable content

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#145]
We need to decide which videos to show, prepare the content and the copy.

**Comment by jellegerbrandy** [comment]
also, I think we can forget about the webtorrent and the centrallly-hosted content that we have in the demo now, and just run evertying from ipfs.

**Comment by ya7ya** [comment]
@jellegerbrandy Yeah, Once I finish this week optimization I'll clear the other methods and IPFSify the videos 👍

**Comment by geckoslair** [comment]
@felipegaucho needs to make a selection first

**Comment by geckoslair** [comment]
it's related to Video content #180

**Comment by felipegaucho** [comment]
Selection for the mvp: https://docs.google.com/spreadsheets/d/1epVyYWi3VzxC_VMyc6p6eyYJF1Env2B1OM6bXc3lEcU/edit?usp=sharing

So we need to manually do thumbs for these dimensions #180? If yes, there's rows in the sheet and we can do it :)

**Comment by jellegerbrandy** [comment]
just to make sure: these are all free for us to use?

**Comment by geckoslair** [comment]
@felipegaucho thumbs are not only for fb or twitter. We needed also for playlist within the app and the oembed service. I think that a first iteration could be the following:

- 1200x1200 px for **twitter** and **oembed**
- 1200x627 px (not 630 as i say in #180 )  for **facebook**. 

for playlist thumbnail i don't have idea @jrgarou @pedrocasa  ?

**Comment by jellegerbrandy** [comment]
hey @ya7ya , it's not the nicest job to rip the vids from vimeo and youtube, but since you know how to get them "ipfs ready", can i assign this to you?

**Comment by ya7ya** [comment]
@jellegerbrandy , Yeah Assign away dude 👍

**Comment by jellegerbrandy** [comment]
Ok, this is working, but the process is not smooth yet.

At the moment, the procedure requires two different actions:

- register tsome basic info about the vids in the videoRegistry on the blockchain (code is in `api` branch on `paratii-contracts` and in a terrible terrible state)
- add rest of video info + playlists directly in mongodb (--> code is in devops repo)
