### ISSUE TITLE
do not show fiat value on purchasing modal

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#148]
Now, the modal for purchasing a video shows some lke "10$, 22PTI". Of course, we do not know the dollar value. Can we remove this and just leave the PTI value?

**Comment by pedrocasa** [comment]
For now on ( test version ) make sense for me to leave just the PTI value.

**Comment by jrgarou** [comment]
@jellegerbrandy @pedrocasa I'll update the [unlockVideo](https://github.com/Paratii-Video/paratii-player/blob/master/imports/ui/components/modals/unlockVideo.html#L33) removing/hiding the _dollar_ information

**Comment by jrgarou** [comment]
I did: https://github.com/Paratii-Video/paratii-player/commit/0674e3b3cdc2823665361a96c796649a0114fd29
