### ISSUE TITLE
UX for error handling

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#149]
[moved here from https://github.com/Paratii-Video/paratii-design/issues/1]

We need some way/place to show errors. 

Here is a list of things that can go wrong when sendign a transaction to the blockchain. (I've taken the buying of a video as an example):

  - No connection to the blockchain 
  - No local wallet
  - Wrong password
  - you don't have enough ETH to pay for transaction costs
  - you don't have enough PTI to pay for this video
  - timeout errors - you sent the transaction, but it is not beging processed
  - this video is not available/registered on the blockchain
  - this video is availalbe, but its price has just changed (and _now_ yhou dont have enough pti)
  - some "uknown error" occurred (on the node)

Question: where and how are we showing such errors?

Perhaps a useful distinction: there are synchronous errors that can be reported immediately (wrong pass, nto enough funds, etc) and asynchronous errors that only occur after a certain time (i.e. the processing errors)

cf. #169

**Comment by geckoslair** [comment]
cf: #169

**Comment by jellegerbrandy** [comment]
This is a duplicate of #169
