### ISSUE TITLE
unlock modal: set the state to 'sending' after submit

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#150]
The unlock-video modal has the following states:

- success
- error
- sending... (set by adding a `loading` class to the modal element, disables the submit)

Success is working, error is workign (but does not give info about error - cf. #149). Sending is not yet hooked up.

**Comment by geckoslair** [comment]
cf: #169

**Comment by jellegerbrandy** [comment]
It needs some styling, but some rudimentory text is there.
