### ISSUE TITLE
The necessities of Tiny/Mini options on the share modal

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-player#152]
I wonder if it's really necessary to give the user those resolution options MINI & TINY when he's going to share the video. Maybe we shouldn't give the user this option and just make it automatically responsive (adapting to the viewer's screen size)
Give me your opinion, on which circumstances would those options help or worsen the user experience?

![capture_03](https://user-images.githubusercontent.com/30123644/31635804-e77479ba-b2a6-11e7-8530-ff8a6bb87c4f.JPG)

And what would be the behavior of a pay-per-view video when the user chooses the "autoplay" option?

@jellegerbrandy 
@jrgarou 
@geckoslair 
@felipegaucho

**Comment by geckoslair** [comment]
@pedrocasa 

As i told in #170 "mini" and "tiny" are think basically to reduce player features.
When a user select "mini" or "tiny" we set a suggested sizes: 570 or 340.

We can change "mini" and "tiny" labels in favour of something else like: "lite", "minimal", "essential" etc. ... don't know =)
Another idea could be: we can remove "mini" and "tiny" in favour of a set of settings that customize UI (as Vimeo).

Let's disable Autoplay for all pay-per-view video. #190
