### ISSUE TITLE
wire "signUp" and "signIn" modals

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#155]
The modals `modal_sign_up` and `modal_sign_in` need to be writed to the signup machinery (I mean they need to work :-)

**Comment by jrgarou** [comment]
@jellegerbrandy @geckoslair @eliawk 
Is this for the **october sprint**?
![image](https://user-images.githubusercontent.com/320157/31946716-4dbf6346-b8b1-11e7-8a7f-254c01f61432.png)

**Comment by jrgarou** [comment]
### login flows
**signin**
Can we implement the forgot password screen(email validation, get success on send and then receive a link that open the modal and finish the process)?

**signup**
I validate all errors(username+email, password and email already exist) but always return this error:
![image](https://user-images.githubusercontent.com/320157/31965386-034420ec-b8e6-11e7-9fbc-146445442597.png)

**Comment by jellegerbrandy** [comment]
@jrgarou: in what case do you get the error on signup?

**Comment by jrgarou** [comment]
@jellegerbrandy Always when I send the form(even when everything was validate)

**Comment by jellegerbrandy** [comment]
ok, it's a bug, can you make a separate issue for it @jrgarou?

**Comment by eliawk** [comment]
they work now, i close the issue!
