### ISSUE TITLE
configure email on server

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#158]
meteor needs to be able to send mails

**Comment by geckoslair** [comment]
Maybe ses by amazon @ya7ya

**Comment by ya7ya** [comment]
@geckoslair Sorry for the late reply. I missed the notification. Yes, I'll check SES.

**Comment by geckoslair** [comment]
@ya7ya i was just kidding. @jellegerbrandy tell me about your love for amazon :D

**Comment by ya7ya** [comment]
@geckoslair lol 😆 , Nah SES will do fine for now, We do need to verify the domain to be used by SES though. 👍

**Comment by jellegerbrandy** [comment]
Amazing though how we started with a "we'll just use bare aws machines so we can leave amazon whenever we want" to "we have elastic IPs now, let's integrate email as well, these load balacer things could be useful too" in like two weeks :-)

**Comment by ya7ya** [comment]
@jellegerbrandy hahaha, yeah, That's how they get ya :D

**Comment by geckoslair** [comment]
email is configured, but let's discuss on better solutions
