### ISSUE TITLE
Design.Mini Purchase/Watch M01-M16, M81-M83

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-player#162]
Issue for purchase process discussion. 
( M01-M16; M81-M83 )

Give me your feedback about the layout and functionality.
 - If you need to refer to a certain page, write the number of the page you are referring to.
 - Not every page is in this flow, check the others Design.Mini issues 

[flow-purchase.pdf](https://github.com/Paratii-Video/paratii-player/files/1416129/flow-purchase.pdf)

**Comment by felipegaucho** [comment]
@pedrocasa great work!

Only comments so far regard M06:

- Sucess -> Suc**c**ess
- Shouldn't M06 be just an intermediary state, and go straight to playing the video once the "loading" ends? (watch the video could become "done", or something like this, and dissappear)

**Comment by jellegerbrandy** [comment]
* M06: felipe is right... the intermediate state should show a "sending..." item (perhaps even animated), which then ends in either "error" or "success". We show the "success" for half a second, then move to M07 without any further user interaction.

* M14: the current "embed" modal has possibility to choose options (fullscreen, etc). What happend to that?

* M13: seems to me superflous (these are options you can go to after choosing the video, i.e. from M11)

* M15 (playlist): needs some work, but I'd put it in backlog for now.

**Comment by pedrocasa** [comment]
- M06: I thought about it with @jrgarou. The interesting thing about keeping this button on is that if the user gets distracted he will not be confused about what happened (both alternatives are OK for me).

- M14: We need to create an issue exclusively for this page. I still don't understand why we need so many options in that modal (is there another way to make it more automatic and simple?)

- M13:  Youtube just keeps the "watch later" button. We can think of something simpler like youtube or remove it once and for all (none of these alternatives makes me uncomfortable )

- M15: Ok, If somebody sees a good reference about it please send me

**Comment by jellegerbrandy** [comment]
Moved discussion about M14 to new issue #170

**Comment by jellegerbrandy** [comment]
* about M06: we can implement it as you designed it - if it turns out not to work in practice, we can always change it.

**Comment by pedrocasa** [comment]
Flow re-uploaded
