### ISSUE TITLE
Design.Mini Wallet M27-M43

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-player#164]
Issue for wallet page discussion.
( M27-M43 )

Give me your feedback about the layout and functionality.

- If you need to refer to a certain page, write the number of the page you are referring to.
- Not every page is in this flow, check the others Design.Mini issues

Our of scope flow!
[flow-wallet.pdf](https://github.com/Paratii-Video/paratii-player/files/1446247/flow-wallet.pdf)

October sprint!
[flow-wallet-octobersprint.pdf](https://github.com/Paratii-Video/paratii-player/files/1447454/flow-wallet-octobersprint.pdf)

**Comment by felipegaucho** [comment]
I'm very comfortable w/ it. Other might still spot UX issues.
"Earn more PTI" was discussed https://github.com/Paratii-Video/paratii-design/issues/2, and probably going out for now.
In M28-M29, dollar values can be omitted for now w/out affecting the layout, I guess.

**Comment by jellegerbrandy** [comment]
A "change profile pic" is missing

**Comment by pedrocasa** [comment]
@jellegerbrandy  M43

**Comment by pedrocasa** [comment]
Re-uploaded

**Comment by jellegerbrandy** [comment]
@pedrocasa : what is missing is also:

* show the keyphrase
* restore your wallet (with a existing keyphrase)

I think they can be two new options hidden behind the gears icon - what do you think?
