### ISSUE TITLE
Design.Mini Search M54-M58

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-player#165]
Issue for search pages discussion.
( M54-M58 )

Give me your feedback about the layout and functionality.

- If you need to refer to a certain page, write the number of the page you are referring to.
- Not every page is in this flow, check the others Design.Mini issues

[flow-search.pdf](https://github.com/Paratii-Video/paratii-player/files/1392122/flow-search.pdf)

**Comment by felipegaucho** [comment]
I like it, and think it should be complimentary to a "search" inside the "playlists", very akin to it, as I mentioned in the "playlists" issue.

**Comment by jellegerbrandy** [comment]
I think there should be a single "discovery" screen - i.e. we should merge this functionality with that of #163. It will simplify both UX as well as development, and I see no point in having a separate screen.

**Comment by jellegerbrandy** [comment]
we should also think of how to handle the near-future situation: we will have very little content, so all the ordering stuff will look slightly ridiculous. I'd propose in a first iteration to just have a general search box (that searches in tags, descriptions, titles, authors) with no further options..

**Comment by jrgarou** [comment]
I do agree with @jellegerbrandy. And discover(y) is a good name too 😀
What I think that is good:

## Option 1: 

- Page title (Discover, Search, Find, Enjoy, Have fun... Could not be _Playlists_)
- **Videos list**
  - A section title(Videos. movies...) with(or not) a search for videos
  - A search videos if there's no search on title
  - Videos list with only 3 videos to make playlists list visible(order by uploaded/views/likes...?)
  - Pagination or load more button

- **Playlists list**
   - Same configuration from Videos list

## Option 2: 

- Page title (Discover, Search, Find, Enjoy, Have fun... Could not be _Playlists_)
- A search videos that changes all content below it:

- **Videos list**
  - A section title(Videos. movies...) 
  - Videos list with 3 videos to make playlists list visible(order by uploaded/views/likes...?)
  - Pagination or load more button

- **Playlists list**
   - Same configuration from Videos list

What you think guys, @jellegerbrandy @pedrocasa @felipegaucho @lupape?

**Comment by felipegaucho** [comment]
I like the 2nd :)

**Comment by geckoslair** [comment]
ok!
what happen when the user is searching? All the content (playlist or videos ) disappear and results (matching videos) appear?
@pedrocasa @felipegaucho

**Comment by jrgarou** [comment]
@geckoslair, if we decide to set the [option 2](https://github.com/Paratii-Video/paratii-player/issues/165#issuecomment-339752309) I believe so: the search filter all content(videos and playlists)

**Comment by geckoslair** [comment]
@jrgarou

how the search playlists works? 

- option one: filter just in playlist matching title/description
- option two: filter playlists that contain video that match the search keyword?

how the search videos (inside a playlist) works? 

We don't have soo much content (40 videos)

**Comment by jrgarou** [comment]
@geckoslair, everything is just an ideia.
Can we apply both? The search playlists show playlists matching title/description **and** that contain video that match the search keyword.

The search videos filter matching title/description.

Maybe we could only filter the videos, and show [all(5) playlist](https://docs.google.com/spreadsheets/d/1epVyYWi3VzxC_VMyc6p6eyYJF1Env2B1OM6bXc3lEcU/edit#gid=0)

**Comment by pedrocasa** [comment]
I agree with @jrgarou 
We should apply both and then make a rule about what is more relevant the playlist title or the video title
 ( the more relevant should appear first in the search  page )

**Comment by pedrocasa** [comment]
I have just one question, If there's no playlist page anymore how can the user create a new playlist or visit the playlists that've just been created ?

**Comment by geckoslair** [comment]
@pedrocasa @jrgarou
i think it's good to discuss about this issue =) but a relevant sorting it's quite premature at this stage (we have also to defined what is relevant for the user, also for video suggestion and other features). Merging video and playlist in the same results set it's quiet a mess (videos and playlist belong to different collections) .

I suggest this: 

- **for the October sprint** we keep divide Playlist navigation (as is at the moment) and Search (that just search in video)
- **after the October sprint** let's discuss what kind of results we excepted when a user search, what is relevant for him, etc. we can devote some time in the next weeks to continue the discussion.

**Comment by jrgarou** [comment]
@geckoslair, It's no so mess =). It's something like spotify/deezer  [search page](https://open.spotify.com/search/results/brasil), but more clear(less results in only 2 sections(videos results and playlists results)).

**Comment by geckoslair** [comment]
I've talk with @jellegerbrandy  about this solution, as you say it's quiet easy to implement. The main problem is the ux when the user search in the mini version.

**Comment by jrgarou** [comment]
I agree with both approaches: 
- [Option 2](https://github.com/Paratii-Video/paratii-player/issues/165#issuecomment-339752309)
- Or create two pages
    - Videos page(with search or not)
    - Playlists page(with search or not)

**Comment by jellegerbrandy** [comment]
* I agree with @geckoslair : for the october sprint, we have a playlists page (with just 4/5 playlists, so no search in playlist needed), and a separate search page for searching in videos (only)
 * Search is a complex issue, and touches many aspects, and also depends very much on the use cases. I think we should discuss the different ideas we have by voice, in a call. perhaps tomorrow, or perhaps after the sprint 
* (I personally still think a combined "discovery page" that does not distinguish between playlists and videos is the best solution (like option 2 but not with divided result sets :-) )
 * One more thing to include in your thoughts: how do we present 100s of results?

**Comment by jrgarou** [comment]
Then we agree with 2 pages(videos and playlits) with search inside(same layout(no for details))?

>One more thing to include in your thoughts: how do we present 100s of results?

@jellegerbrandy, pagination or load more button

What you think, @jellegerbrandy @geckoslair @felipegaucho @pedrocasa ?

**Comment by pedrocasa** [comment]
I don't have a final opinion about it, It's hard to predict what'll be the user behaviour when the player has a lot of videos and what's the best for the user right now

- If we create a unique search/discovery page ( what sounds like a great idea)
We shouldn't forget about how the changes will affect the secondary features of the search and playlist pages ( such as create a new playlist button  )

**Comment by jellegerbrandy** [comment]
[for the october sprint, we just implement text search]

**Comment by jellegerbrandy** [comment]
I have some reservations about the sorting options:


- "sort by price", descending, ascending. Guys. We are not a shop. We are a video platform. What are you going to do with your next 2 hours, watch a movie because it is 1$ cheaper than another? 
- "sort by date". Date of what? Date fo upload? Date of creation?
- there are so many other ways or ordering (alphabetically by title, author, by popularity, by likes, by views) that this selection seems absolutely arbitrary. Who is this for?

I'd seriously consider not doing any advanced search in the player at all.

**Comment by jellegerbrandy** [comment]
these are YT "filter" options:

![image](https://user-images.githubusercontent.com/1306173/32223963-e1e235e2-be3f-11e7-8d2b-16c4709b90a1.png)

**Comment by geckoslair** [comment]
@jellegerbrandy at current stage searchable fields are:
title
description
uploadername
tags
