### ISSUE TITLE
Design.Mini Sign in/up/ Log out M44-M49, M69, M86

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-player#166]
**NB: the designs for the flow are not valid anymore - cf the discussion below**

Issue for Sign in/up/logout pages discussion.
( M44-M49; M86; M69 )

Give me your feedback about the layout and functionality.

- If you need to refer to a certain page, write the number of the page you are referring to.
- Not every page is in this flow, check the others Design.Mini issues

[flow-sign.pdf](https://github.com/Paratii-Video/paratii-player/files/1411112/flow-sign.pdf)

[flow-logout.pdf](https://github.com/Paratii-Video/paratii-player/files/1392095/flow-logout.pdf)

**Comment by felipegaucho** [comment]
M46-M47 : ... _"link **sent** to your email"_.
M49: ... _"on **a piece of** paper and store it somewhere safe"_.

**Comment by jellegerbrandy** [comment]
* there is a bit of a duplicate with #167 , as flow-sign.pdf also contains screens M50-52.
* about logout: we need to think about this better: the player is unusable after logging out. So what is the use case here?
* Electrum (=bitcoin wallet) does somethign I like: it says "here is your 12 word phrase, write it down, blabla", and then on the next screen it asks you to input the phrase (to make sure you did actually back it up).

**Comment by pedrocasa** [comment]
- Sign flow re-uploaded

**Comment by pedrocasa** [comment]
- Sign flow re-uploaded

**Comment by jellegerbrandy** [comment]
I'm bit late with this, but I think the email-confirmation step should not be blocking for account creation. It should be an optional, a nice thing to do and with which to earn some PTI, not an obligation. 
Ie. we should go from M46 to M48. The email confirmation is a separate flow, iniated by the email link.

**Comment by jellegerbrandy** [comment]
A detail: the 12 words have spaces between them. They should not be separated by dashes, which just adds to the confusion for the user.

**Comment by jellegerbrandy** [comment]
The Sign up process should work like this:

* Fill in sign up form M45
* Show the user's ETH account (M48, but without the seed)
* Show the seed (M49). But not as a warning in red, please.
* Ask for confirmation fo the seed (M88)

Some remarks:
* M48, M49 and M88 are blocking.
* We will review the copy in a separate issue

**Comment by felipegaucho** [comment]
See a nice alternative, refined way of asking for confirmation for the seed: https://youtu.be/k42YNyvG8CU?t=2h22m5s

**Comment by pedrocasa** [comment]
@jellegerbrandy  " ... a nice thing to do and with which to earn some PTI, not an obligation.
Ie. we should go from M46 to M48. The email confirmation is a separate flow, initiated by the email link."

Is the email confirmation a good thing for us?

**Comment by jellegerbrandy** [comment]
what do you mean by "a good thing for us"?

**Comment by pedrocasa** [comment]
Just wanted to know why the user should confirm his email if it's not necessary to create an account.

( ok, he earns the PTI  but would he have any advantage besides that? )

**Comment by jellegerbrandy** [comment]
So he can recieve notification from paratii. (Or spam from us :-))
