### ISSUE TITLE
Design.Mini Forgot Password M50-M52

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-player#167]
Issue for Forgot password pages discussion.
( M50-M52 )

Give me your feedback about the layout and functionality.

- If you need to refer to a certain page, write the number of the page you are referring to.
- Not every page is in this flow, check the others Design.Mini issues

[flow-forgot.pdf](https://github.com/Paratii-Video/paratii-player/files/1403154/flow-forgot.pdf)

**Comment by felipegaucho** [comment]
M52: should also contain fields for the 12-word seed and an extra field for confirming the new password (corresponding warning/error message if the 2 passwords don't match, or the seed is wrong)

**Comment by jellegerbrandy** [comment]
The flow is not exactly like this. After submitting the email, the modal should show something like "check your inbox", and the only action is to close this modal.

Then, after the user clicks on the reset link in the email, we show these modals:

1. Insert new password (and confirm)
2. [next screen] insert 12-word seed phrase to regenerate yr wallet

**Comment by pedrocasa** [comment]
There's also another thing that can be a problem in the future. The user shouldn't have the option to write his email address ( the player are going to send an email exclusively for the address that is already registered in the profile )

**Comment by pedrocasa** [comment]
flow re-uploaded

**Comment by jellegerbrandy** [comment]
Please see #248
