### ISSUE TITLE
Design.Mini My videos M60-M68

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-player#168]
Issue for My videos pages discussion.
( M60-M68; ... )

Give me your feedback about the layout and functionality.

- If you need to refer to a certain page, write the number of the page you are referring to.
- Not every page is in this flow, check the others Design.Mini issues

[flow-myvideos.pdf](https://github.com/Paratii-Video/paratii-player/files/1392110/flow-myvideos.pdf)

**Comment by jellegerbrandy** [comment]
There are actually two different types of upload:

* upload a file from local disk or from an URL. Can work much as you show.
* upload/convert from youtube, vimeo, ... That needs access to those platforms, so we need the user to log in there

Some other remarks:
* data model: we probably also want to add fino about copyright, ownership, perhaps even intended audience
* tags - do we have a fixed set or is this free text?
* if we have upload, we need the full CRUD thing: a way of visualizing "your" videos, editing and deleting them.

On the longer term, we also want to talk about advertising in these screens. This is somethig to keep in mind.
