### ISSUE TITLE
Design.Mini Error Messages M53, M70-M80

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-player#169]
Issue for Problems pages discussion.
( M53, M7-M80)

Give me your feedback about the layout and functionality.

- Not every page is in this flow, check the others Design.Mini issues
-As we don't know all the possible problems I didn't name the pages

![002](https://user-images.githubusercontent.com/30123644/32442352-42a1ff92-c2e2-11e7-9d25-e14b9ead9c3b.png)

**Comment by jellegerbrandy** [comment]
It would be useful to have some general guidelines for showing errors, and show them in a uniform way. 

roughly the errors  fall into 3 categories:

 1. Error on input field in form
 2. Error after submitting a form (such as buying a  video or sending PTI or ETH)
 3. Errors that happen asyncrhonously (such as 'connection is lost' type of errors)

about (1): I think showing the error in the input field is not good. Like this the user cannot see what he typed anymore and so is missing a part fo the info he needs to correct the error. For example, if I make a typoe in the address I want to send ETH to, and i get an "invalid address" error, I want to  be able to check what I typed.

Wrt.(2), the "after submit" errors. We have two different "layouts" now - the ones after trying to buy a video, and the ones after trying to send PTI/ETH. **these need to be the same** because they are bascially the same actions. I personally think the buying-video errors are cute, but they less easy to tweak (mostly because they ahve to be really very short messages to fit into that space).

**Comment by jellegerbrandy** [comment]
*wrt october sprint* Since the wallet is out of scope for the october sprint, we can put M73-M75 aside from now, and go with the nice M70-M72.

**Comment by geckoslair** [comment]
@pedrocasa regards M79, i think it's better to show the message in a non-blocking notification, like gmail for example. What you think?
![image](https://user-images.githubusercontent.com/4333157/31820831-4b745062-b5a3-11e7-9482-03a4b4f44a2d.png)

**Comment by pedrocasa** [comment]
@jellegerbrandy  @geckoslair 
(1) Maybe the solution for the error on an input field is to use non-blocking notification in every circumstance ( as @geckoslair  mentioned for M79 )

![m77](https://user-images.githubusercontent.com/30123644/31907388-71724fa0-b812-11e7-8c06-d52ad2a6f598.png)
![m73](https://user-images.githubusercontent.com/30123644/31907390-719553ba-b812-11e7-81e0-7e92707ed63c.png)

gimme your opnion about it please

**Comment by pedrocasa** [comment]
@jellegerbrandy @geckoslair @felipegaucho 
(1) Maybe the solution for the error on an input field is to use non-blocking notification ( as @geckoslair mentioned for M79 



( version 1)

 -  texts are just placeholders

![m73](https://user-images.githubusercontent.com/30123644/31911756-81767904-b820-11e7-8b7c-a11ff89e176d.png)
![m76](https://user-images.githubusercontent.com/30123644/31911757-81c3c3da-b820-11e7-8ea4-9bcb649996ee.png)

( version 2) 

 -  texts are just placeholders

![m73](https://user-images.githubusercontent.com/30123644/31911318-08d0f98a-b81f-11e7-83a1-f09fdb784463.png)
![m76](https://user-images.githubusercontent.com/30123644/31911319-08ef7bb2-b81f-11e7-9954-e5e1a3508827.png)

Gimme your opniom about it please

**Comment by geckoslair** [comment]
@pedrocasa love both, but i prefer the version 2 (i love verbose actions).

As for the modal we have to provide notifications/messages in every moment (maybe on the top of the window). These are some examples of what we could do: http://github.hubspot.com/offline/docs/welcome/.

**Comment by pedrocasa** [comment]
tnks
soon I'm gonna open an issue about it ( notifications )

**Comment by pedrocasa** [comment]
re-uploaded the flow ( categories (1) and (2) )

- we should put a "cant leave blank" error visual feedback on every text box that has to be filled (im suggesting a red underline on boxes that have an error) plus the top error bar saying what the user did wrong
- I'll upload as a pdf until I find a viable way to prototype

**Comment by pedrocasa** [comment]
Found it on medium

https://uxplanet.org/mobile-ux-design-user-errors-1ad1f5d664f9

**Comment by pedrocasa** [comment]
https://uxplanet.org/mobile-ux-design-user-errors-1ad1f5d664f9

**Comment by jellegerbrandy** [comment]
very nice article

**Comment by pedrocasa** [comment]
Working on errors that happen asynchronously (3)

![m79](https://user-images.githubusercontent.com/30123644/32002379-217b4a32-b97b-11e7-9ccd-641a4783b286.png)
![m80](https://user-images.githubusercontent.com/30123644/32002380-219889da-b97b-11e7-9f18-1656f207e9e4.png)
![m78](https://user-images.githubusercontent.com/30123644/32002381-21c125c0-b97b-11e7-9728-3e59136a33ef.png)

gimme your opinion when it's possible 

@jellegerbrandy @geckoslair @eliawk

**Comment by jellegerbrandy** [comment]
I think it is too invasive. Connection problems are pretty normal, we just want to inform the reader, not scare him away. I'd say a bit smaller, and perhaps not red.

**Comment by geckoslair** [comment]
agree with @jellegerbrandy, maybe just invert colors (red font over white bg).

**Comment by jrgarou** [comment]
The design is fine for me. Maybe we can set styles for every error type.
Connection errors could be on video.

Can we list all possible errors?

**Comment by pedrocasa** [comment]
I understand it and agree that simple errors don't need to be that invasive

As @jrgarou said It's important to have a list of all possible problems and which are more "serious"  and which are just every day possible problems. 

It would be great if we can list these errors in the 3 categories that @jellegerbrandy mention in the first comment of this issue ( and even write what the user should do when it happens )

**Comment by pedrocasa** [comment]
I understand it and agree that simple errors don't need to be so invasive

As @jrgarou said, it's important to have a list of all possible problems and which ones are more "serious"  and which are just "casual" problems. 

It would be great if we could list these errors in the 3 categories that @jellegerbrandy mentioned in the first comment of this issue and write what the user should do when it happens

**Comment by jellegerbrandy** [comment]
Realistically, we will never have a ist of **all** possible problems. There
will always be situation we have not thought of, or the necessity to
distinguish types of errors that we first thought could be conflated, etc
etc.


We need a easily reusable error handling for each type of error, and a
generic UI/UX design that we can recyle easily..

**Comment by pedrocasa** [comment]
Make sense
gonna work on that

**Comment by pedrocasa** [comment]
@jellegerbrandy tell me what you think about this ( image bellow)

![002](https://user-images.githubusercontent.com/30123644/32373077-9f72019c-c07e-11e7-9346-d617dcd539e8.png)

**Comment by pedrocasa** [comment]
@jellegerbrandy please tell me what you think about it

- I tried to put a description of the problem in the situation (3) but it did not fit

![002](https://user-images.githubusercontent.com/30123644/32373580-0c34455e-c081-11e7-9580-2d72208b2e08.png)

**Comment by pedrocasa** [comment]
@jellegerbrandy please tell me what you think about it

- I tried to put a description of the problem in the situation (3) but it did not fit

![002](https://user-images.githubusercontent.com/30123644/32373494-a8415f1e-c080-11e7-85b9-4e624367f94b.png)

**Comment by pedrocasa** [comment]
Re-uploaded it

**Comment by eliawk** [comment]
Now there is a system to show errors in the player and in modals. we just need to define which errors and some right copy

**Comment by jrgarou** [comment]
@jellegerbrandy @eliawk @geckoslair I pushed, to [frontend branch](https://github.com/paratii-Video/paratii-player/tree/frontend), the alert component that @eliawk, @pedrocasa and I developed.

- To call global alerts use the `import { globalAlert } from '/imports/lib/utils.js'`.
- To call alerts inside the modal use the `import { modalAlert } from '/imports/lib/utils.js'`.

### styles(@pedrocasa feel free to change the colors)
- `globalAlert/modalAlert('<strong>Your message here</strong>. Some text in here')`
![image](https://user-images.githubusercontent.com/320157/32523750-dd64e61c-c403-11e7-8861-359a443acdb4.png)

- `globalAlert/modalAlert('<strong>Your message here</strong>. Some text in here', 'success')`
![image](https://user-images.githubusercontent.com/320157/32523837-3a861e4c-c404-11e7-8fdd-d064b28182a9.png)

- `globalAlert/modalAlert('<strong>Your message here</strong>. Some text in here', 'warning')` 
![image](https://user-images.githubusercontent.com/320157/32523899-805d1786-c404-11e7-9ef3-488d6aa3981c.png)

- `globalAlert/modalAlert('<strong>Your message here</strong>. Some text in here', 'error')`
![image](https://user-images.githubusercontent.com/320157/32523951-b38b0b54-c404-11e7-82ea-12ed64466af0.png)


### options
`globalAlert('<strong>globalAlert</strong> and <strong>modalAlert</strong> You can <a href="/profile">go to a page</a> or <a href="/profile" data-showmodal="confirmLogout">open a modal</a> or <a href="/profile" data-showmodal="confirmLogout" data-closealert>open a modal and close the alert</a>', 'error')`
- `href="/page"` works fine;
- `data-showmodal="modaltemplate"` on a <a> to open a modal;
- `data-closealert` to close the current alert.

![image](https://user-images.githubusercontent.com/320157/32524028-09ad6298-c405-11e7-9c49-9e8f20e3b533.png)

**Comment by jellegerbrandy** [comment]
Ok, very cool. I moved these last remarks to the wiki, it seems to be a great start fo documenting our work a bit: https://github.com/Paratii-Video/paratii-player/wiki/Code

I am closing this issue in favor of more generic issue such as #244
