### ISSUE TITLE
login and registration modal: inserted text should be a darker color

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#183]
now, the inserted text seems a place holder.

![image](https://user-images.githubusercontent.com/1306173/32048113-989d61f4-ba48-11e7-9480-20f00e51824d.png)

**Comment by jrgarou** [comment]
@jellegerbrandy fixed https://github.com/Paratii-Video/paratii-player/commit/d49acc52139be02d47790ac3730799baec52cc8f
