### ISSUE TITLE
make regenerateKeystore modal pretty

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#184]
This new modal needs to be styled - it's called 'regenerateKeystore'

![image](https://user-images.githubusercontent.com/1306173/32053922-f7ebac56-ba5c-11e7-844b-e06f03b02e76.png)

**Comment by jrgarou** [comment]
@jellegerbrandy done https://github.com/Paratii-Video/paratii-player/commit/bfe3aa571de97be12969d9392979cdcd33265098
