### ISSUE TITLE
sharing modal: telegram and whatsapp

### ISSUE THREAD

**Issue by geckoslair** [Paratii-Video/paratii-player#185]
- [x] i'd like to add Telegram because the sharing url is cross device (whatsapp it's not).
- [x] we have to remove whatsapp on no mobile device

what about?

i've added telegram with whatsapp icon on dev

**Comment by geckoslair** [comment]
Hi @jrgarou ! about:

- [x] we have to remove whatsapp on no mobile device

Do you have some news? Can i help you?

**Comment by jrgarou** [comment]
@geckoslair Can we set a mobile detect class on `main-app`?
I can fix this with css, but we got a better control if we do like this.

**Comment by geckoslair** [comment]
@jrgarou good idea! I create an issue.

**Comment by geckoslair** [comment]
depending also on #240

**Comment by geckoslair** [comment]
@jrgarou hi man!
i've pushed on dev the new helper. Now i'm adding to the body class the following classes:

  this.classes += (this.isMobile()) ? 'mobile ' : ''
  this.classes += (this.isPhone()) ? 'phone ' : ''
  this.classes += (this.isTablet()) ? 'tablet ' : ''

You can play with them as you prefer, if no class is provided so is desktop. Let me now.
