### ISSUE TITLE
Implement search 

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#187]
this is a precondition for #165

**Comment by mrocha94** [comment]
I read the implementation and I recommend using [$text](https://docs.mongodb.com/manual/reference/operator/query/text/) for Mongo search.

Another thing, is it worth keeping two documents one for playlist and another one for videos?

**Comment by jellegerbrandy** [comment]
@mrocha94 , for yr first remark, can you add a link to the code?

The second remark I do not really get. Is yr question: "why are there two collections: one for playlists, one for videos"?

**Comment by mrocha94** [comment]
Just change the query from $or [search.js#L43](https://github.com/Paratii-Video/paratii-player/blob/ca7c8663b6cb2505a16b745c09d3eea5f2856cc5/imports/ui/pages/search/search.js#L43) to something like this:

```
db.videos.find(
   { $text: { $search: queryKeywords } },
   { score: { $meta: 'textScore' } }
).sort( { score: { $meta: 'textScore' } } )
```
And we have to create a index for every field that we want to search with:

```
db.videos.ensureIndex(
      { title: 'text' },
      { description: 'text' },
      { 'uploader.name': 'text' },
      { tags: 'text' })
```

[Here](https://blog.codecentric.de/en/2013/01/text-search-mongodb-stemming/) explains why Mongo is really good on searches. 

About the second part, you are right, I meant collections. So: why are there two collections: one for playlists, one for videos?

**Comment by jellegerbrandy** [comment]
@enricocicconi : mateus is right about the mongo search..

Two collections: Good question.  For getting search to work across both videos and playlists, it is more convenient to have a single collection. For managing permissions and business logic, it is convenient to have two different collections. So to me, there is no clear best choice. For now (october sprint), we'lll keep them separate - we can reconsider later.

**Comment by geckoslair** [comment]
@mrocha94 good point ! we can add this and sorting score desc by default. What you think? i can do it
