### ISSUE TITLE
"next up" (you may also like, related) videos

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#189]
#162, M12

- [x] We need a (server-side) function which could look like

`nextUpVideos(videoId, userId)` that returns an array with 6 video arrays. 

first iteration can just be 6 random vids.

- [x] integrate this with palyer (when video ends, thes nextup vids need to be shown)

- [ ] make it pretty

**Comment by geckoslair** [comment]
@jellegerbrandy this feature if it's just available if a video is not playing within a playlist, right?

**Comment by jellegerbrandy** [comment]
yes

**Comment by geckoslair** [comment]
> We need a (server-side) function which could look like

implement as publish in videos.js -> relatedVideos
> integrate this with palyer (when video ends, thes nextup vids need to be shown)

it shows just if the video is played outside a playlist

**Comment by geckoslair** [comment]
@jrgarou fill free to "make it pretty" =) merged on dev
