### ISSUE TITLE
Navigate into playlists videos with skip button when video is locked

### ISSUE THREAD

**Issue by jrgarou** [Paratii-Video/paratii-player#196]
It is not possible navigate into playlists when the video is _locked_.
We can to keep the navigation buttons(skip) or create another way to do it.

![image](https://user-images.githubusercontent.com/320157/32200529-42a34a9c-bdb9-11e7-978f-8a6e2c65a636.png)

**Comment by pedrocasa** [comment]
The user can click on the channel and there we show all the entire playlist

**Comment by jellegerbrandy** [comment]
I think that the "next"/"skip" button should just go the the next item in the playlist. Always, also when the video is locked. Right?

**Comment by pedrocasa** [comment]
I have a preference for the first one

![skip](https://user-images.githubusercontent.com/30123644/32513060-19dad472-c3e0-11e7-9980-33b30cb6f445.png)
@jellegerbrandy  @jrgarou  @felipegaucho

**Comment by pedrocasa** [comment]
@jrgarou  did not find the last examples very appropriate in comparison with the rest of  the UI ( follow the rules already applied to the other buttons)

his suggestion 

![capture](https://user-images.githubusercontent.com/30123644/32516005-04fd577e-c3e9-11e7-9e53-ac442e20c257.JPG)

**Comment by jrgarou** [comment]
It's done, guys @pedrocasa @jellegerbrandy 
https://github.com/Paratii-Video/paratii-player/commit/e7ccc46f7188f6f094b912e9526873921db30932
