### ISSUE TITLE
refactor opening/closing of modals

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#197]
The wanted setup:

* a function: `showModal('modal-content-template', {option1: optionval, ...})` that will either (a) if no modal is open, open a new modal showing `modal-content-template` or (b) if a modal is open, replace thecontent of the modal witht he given content
* use only `showModal` and `Modal.hide()` in the code

Things to do:

* define `showModal`
* refactor code and tests
* rename `userModal` template to something more generic (`modalContainer`?)
* rename `setTemplate` to `contentTemplate` (?)

**Comment by eliawk** [comment]
It's all done! @jellegerbrandy dow you close the issue?
