### ISSUE TITLE
sharing modal: add icon for telegram

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#199]
![image](https://user-images.githubusercontent.com/1306173/32219023-15273c8a-be2d-11e7-8c11-27a120d88dac.png)

Also the height needs to be fixed - depends on #197 

ref #170

**Comment by pedrocasa** [comment]
If needed https://we.tl/7RAl3pHZTN ( telegram svg )

**Comment by jrgarou** [comment]
@jellegerbrandy done https://github.com/Paratii-Video/paratii-player/commit/0fcbff1368fe4f41ec6dd1c3e177915770903d5c
