### ISSUE TITLE
Sharing text

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#201]
now we have sharing buttons for email, whatsapp, telegram etc.
As of speaking, we are just sharing a link to the player.
 
We probably want to decorate the messages with a bit of text, something like "look at this cool video I found: " - or perhaps something more like "watch this video in the decentralized Paratii Player".

**Comment by geckoslair** [comment]
there also the "share via email" text body to make it cooler!

**Comment by geckoslair** [comment]
waiting for copy! @felipegaucho

**Comment by felipegaucho** [comment]
Correct me where the contexts are wrong:

- Facebook: no custom copy.
- **Twitter**: 🎬 Worth a watch: *title*
_(à lá what [Revue does](https://twitter.com/ParatiiVideo/status/902980684473622529) when you share a newsletter of theirs)_
- **WhatsApp**: no custom copy (**_can we @geckoslair ? I have never seen_**).
- **Telegram**: no custom copy (**_can we @geckoslair ? I have never seen. What I usually see are the "instant view" boxes, which, in our case, would contain thumb, title, description and url preview, from what I'm familiar with_**).
- **Email**:
_From (name)_: "First Name" "Last Name"
_Subject_: You have to check this video I found (from Paratii with 💙)
_Copy_: Ay! This video reminded me of you. _**Cool note**_: the system behind the thing has no owner or servers, so videos spread by hopping from computer to computer, pretty much like this one I'm sending now. _**Best part**_: it's not like Tubes where they control what goes up, what goes down and where the money flows to. Here you get paid for watching stuff while your computer works a bit in the background. Only thing you got to do is give your name and email. Anyway, just give it a play:
_video_ 
_button for "Join Paratii"_ 

(@pedrocasa what do you think? Any idea as for this email?)

_**Note**_: clicking on "Telegram" on a desktop leads me to a "join group" page referring to the video's URL (a weird redirect). I've followed whatsapp option will vanish on desktop. Suppose telegram too?

**Comment by geckoslair** [comment]
> Facebook: no custom copy.

customizable if needed
https://stackoverflow.com/questions/5023602/facebook-share-link-can-you-customize-the-message-body-text

> (à lá what Revue does when you share a newsletter of theirs)

ok!

> WhatsApp: no custom copy (can we @geckoslair ? I have never seen).

yes we can =)

> Telegram

~~just the link~~ also the text, telegram has a cross platform client and also a cross platform share link. i'd like not to hide on desktop. Can you tell me more about your telegram issues?

> Email

nice! we can also have fun with a minimal template.

**Comment by geckoslair** [comment]
mini roadmap

- [x] twitter - could be extended more with https://dev.twitter.com/web/tweet-button/parameters
- [x] whatsapp - as twitter
- [x] whatsappdesktop :new:  - as twitter
- [x] telegram - as twitter 
- [ ] mail


about email:

- from: First Name - Last Name -> we have just First Name or  Nick Name . Currently "from" field is: 'Paratii <sharing@player.paratii.video>'

- template ideas? :warning: html it's quite limitate inside email client

**Comment by geckoslair** [comment]
@pedrocasa @felipegaucho 

Mail pending =) let's talk about templates!

**Comment by pedrocasa** [comment]
just have one doubt
Imagine if there is one famous video that is embedded in a lot of web pages and it was shared by email. If we show a link what link should we show in the email? (the one that the person watched or an only-video page link )

Or is it possible for embedding the iframe on the video itself?

**Comment by geckoslair** [comment]
actually we show the video link =)

**Comment by jellegerbrandy** [comment]
meaning: the link that is shared is of the form https://player.paratii.video/etc, i.e. you are not sharing the link of the surroundign web page, but of the video itself.
(And yes, this implies a certain centralization)

**Comment by geckoslair** [comment]
@felipegaucho @pedrocasa @jellegerbrandy 

This will be our sharing template layout.

![screenshot--2017-11-28-14-02-26-102](https://user-images.githubusercontent.com/4333157/33321157-f513d6a0-d444-11e7-84b9-829f26ac66d4.png)

**Comment by geckoslair** [comment]
waiting for deploy on staging

**Comment by geckoslair** [comment]
deployed! template available on staging
