### ISSUE TITLE
play button must be disabled until video is actually ready for playing

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#203]
Reproduce:

1. go here: https://staging.paratii.video/play/8?playlist=4
2. Click on "play"
3. See a black screen (until the vid s downloaded, which may take ages)

The paly button must be disabled until the vid is ready to play. 

(Once we have implemented #154 , this behavior may cahnge)

**Comment by eliawk** [comment]
@ya7ya / @jellegerbrandy  is there any "videoIsReady" method, or something to check if there is enough data to start the streaming?

**Comment by geckoslair** [comment]
think that #236 is rising in priority

**Comment by jellegerbrandy** [comment]
I think this is superseded by the plands to migrate to Clappr, plus the fact that we now have #154 . Closing
