### ISSUE TITLE
if your balance is too low to afford to pay for a video,....

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#205]
if your balance is too low to afford to pay for a video, clicking on "buy video" should let you know this and give you some ideas to get PTI (instead of just showing the modal)

**Comment by pedrocasa** [comment]
![capture](https://user-images.githubusercontent.com/30123644/32459966-5f25b34e-c318-11e7-8a08-206b89975595.JPG)

**Comment by eliawk** [comment]
@jrgarou maybe you could just implement this with the new global alert!
