### ISSUE TITLE
What to show on the profile page for the october sprint

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#209]
We have a nice and detailed design in #164. however, it contains a lot of functionality that is out of scope. 

I propose to 

* hide the action buttons that we are not using. So all the send/receive buttons will be hidden
* also hide "transaction history" link
* also hide the "filecoin" tab

Design: [flow-wallet-octobersprint.pdf](https://github.com/Paratii-Video/paratii-player/files/1447454/flow-wallet-octobersprint.pdf)

**Comment by pedrocasa** [comment]
![capture_01](https://user-images.githubusercontent.com/30123644/32229148-4fd67f30-be37-11e7-8ba6-6a74c7f832f8.JPG)

**Comment by bent0b0x** [comment]
Is there an asset in the app already for the gear/settings icon in the top-right of this mock-up? I cannot seem to find another example of it in the player.

**Comment by bent0b0x** [comment]
Another question, probably for @pedrocasa regarding the back button next to the user's name in the profile view. Where exactly is that supposed to take you? It could take the user to whatever their previous page was, but what if they have navigated directly to the profile page, for example?

**Comment by bent0b0x** [comment]
Also, to which view should the "Earn More PTI" link take you?

**Comment by pedrocasa** [comment]
Hello ben,
- it's not already on the player but you can see the design of it in the issue #164
- yes, it takes d user for the previoua page. There's no way to the user go directly for the profile page (  i.e. spotfy flow  )
- There'll be no more earn more pti buttons

**Comment by bent0b0x** [comment]
Got it, thanks! Do you have an `svg` file for that icon that you could send? I only see it as part of a pdf. Or, if it is typical on this team for FE devs to generate the SVGs themselves just let me know!

**Comment by bent0b0x** [comment]
Is there a mock-up for the modal content when you click on "Earn more ETH"?

![image](https://user-images.githubusercontent.com/7697924/32419140-8e87599c-c243-11e7-9387-e722d2e8d0b2.png)

I see this for PTI but cannot find a corresponding copy for ETH. If they are the same except for the PTI/ETH unit, let me know!

**Comment by jellegerbrandy** [comment]
Actually, we had more or less decided (elsewhere) that this "earn more pti" information info should not be presented to the user in these modals, but on the "corportate" website. So I'd say it is better to remove  teh "earn more PTI" link

**Comment by pedrocasa** [comment]
Yeah, I've forgotten 

I have already told ben on gitter
my mistake

**Comment by pedrocasa** [comment]
![m27](https://user-images.githubusercontent.com/30123644/32458902-05ecad9e-c315-11e7-9f93-cd54bee293a9.png)

**Comment by bent0b0x** [comment]
@pedrocasa looked at the re-uploaded design. Will work on implementing this week!

I did have another Q for you and @jellegerbrandy . I see in the designs of a few pages (including profile) a back button and a full-screen button (in the top-right). Is this a design pattern that will ultimately be on every page? If so, Jelle do you know if this has been implemented anywhere in the app yet and if it is re-usable? If not, happy to do that for the profile re-design.

Also, is the full-screen button supposed to simply take the whole `iframe` full-screen?

**Comment by pedrocasa** [comment]
- "Is this a design pattern that will ultimately be on every page?" 
Almost every page, but when a modal popup it'll be no available to any action

- "Also, is the full-screen supposed to simply take the whole iframe full-screen?"
 Yes

**Comment by jellegerbrandy** [comment]
:heart:
