### ISSUE TITLE
redirect user to / if she arrives at the /profile page and is not logged in

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#212]

**Comment by eliawk** [comment]
yes but we are in an empty page. maybe would be better to redirect the user to the home ig is not logged in?

**Comment by jellegerbrandy** [comment]
I think that if a user requests the `/profile` URL, she will be expecting to see the profile page. If she is logged in, we show it to her; if she is not logged in, she needs to log in (or crate an account) to see it, so we ask her for her credentials, and then show her the profile page.

I think redirecting her to another page of our choice would be confusing here.

**Comment by jellegerbrandy** [comment]
Yes, lets do that.
