### ISSUE TITLE
show errors on signin

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#217]
Now, if you give the wrong password (etc), there is no feedback at all...

(also: write tests!)

**Comment by jrgarou** [comment]
@jellegerbrandy @eliawk For that we need to implement the @pedrocasa warnings.

**Comment by jrgarou** [comment]
@eliawk @jellegerbrandy Done https://github.com/Paratii-Video/paratii-player/commit/2a39726bb91afa9c64644b3010365e1e110c4682
