### ISSUE TITLE
improve copy of sharing/embed modal

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#225]
On "sharing/embed modal":

* "Get Embed" --> "Embed video"
* title "Embed" --> "Embed video"
* above the embed code add "Add the following code to your website"
* 
![image](https://user-images.githubusercontent.com/1306173/32434098-6b3803b6-c2dd-11e7-894e-7b2f48308ff5.png) 
![image](https://user-images.githubusercontent.com/1306173/32434122-7ab61d0a-c2dd-11e7-9b6a-9630d9e8665a.png)

**Comment by pedrocasa** [comment]
@jrgarou

**Comment by jrgarou** [comment]
@jellegerbrandy @pedrocasa done https://github.com/Paratii-Video/paratii-player/commit/52e330aea4b540414e10a5feae8283c50ed12052
