### ISSUE TITLE
how to show more than 6 (or 9?) elements in a playlist

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#228]
What do we do if the number of items does not fit on the page? This pertains to the list of playlists, as well as to the list of videos in a playlist, and also to the search results.

- 1 scroll. (not so nice in an iframe, i vote against)
- 2 paging (i.e. "next page/prev page")
- 3a Neither paging nor scroll, just show the first 6/9 results and ignore the rest
- 3b Neither paging nor scroll, and limit the size of playlists to 6 (or 9) vids

**Comment by pedrocasa** [comment]
I designed it to work as a scroll page ( is an option where the elements do not get so tight )
If we do not want to use a scroll page the best option is to add next/prev buttons ( Options 3a and 3b sounds frustrating to me ). The only problem is that I'm gonna have to decrease all the thumbnails sizes and maybe remove some features on the Mini mode ( IE order by relevance M59 )


This is a very important decision, it would be nice if everybody participates.
@jrgarou  @bent0b0x  @enricocicconi  @felipegaucho

**Comment by pedrocasa** [comment]
- gonna make some tests as we discuss about it

**Comment by felipegaucho** [comment]
Agree that scrolling is bad. I wouldn't be so bothered by having 6 results and then "go to paratii.video to see more". But next pages also seem reasonable if they don't place a burden on performance.

**Comment by pedrocasa** [comment]
![search alternatives](https://user-images.githubusercontent.com/30123644/32455790-7f029f46-c30a-11e7-9354-ee281ebfa2b8.png)

**Comment by pedrocasa** [comment]
![search alternatives](https://user-images.githubusercontent.com/30123644/32457489-739a849c-c310-11e7-926a-9bfeef205e99.png)

**Comment by geckoslair** [comment]
@pedrocasa I vote for 2

**Comment by jrgarou** [comment]
@pedrocasa I vote for 2

**Comment by jellegerbrandy** [comment]
me too 2

**Comment by jellegerbrandy** [comment]
So (2) it is. Opened a new issue for it: #260
