### ISSUE TITLE
"signup" text overlaps signin button

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#231]
![image](https://user-images.githubusercontent.com/1306173/32436269-c98b0b24-c2e3-11e7-81b5-57c015efa622.png)

**Comment by pedrocasa** [comment]
we should follow  this guide https://github.com/Paratii-Video/paratii-player/issues/169

**Comment by pedrocasa** [comment]
@jrgarou

**Comment by jellegerbrandy** [comment]
Seems fixed to me
