### ISSUE TITLE
Changes on M12 ( You May Also like)

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-player#239]

**Comment by pedrocasa** [comment]
As Jelle Said on the #162 the 3 dots on the thumbs  ( options ) are superfluous 
If you see the flow I changed the 3 dots button for a watch later button ( to keep a experience like youtube )

**Comment by pedrocasa** [comment]
As Jelle Said on the #162 the 3 dots on the thumbs  ( options ) are superfluous 
If you see the flow I changed the 3 dots button for a watch later button ( to keep a experience like youtube )

**Comment by pedrocasa** [comment]
As Jelle Said on the #162 the 3 dots on the thumbs  ( options ) are superfluous 
If you see the flow I changed the 3 dots button for a watch later button ( to keep an experience like youtube )

**Comment by pedrocasa** [comment]
As Jelle Said on the #162 the 3 dots on the thumbs  ( options ) are superfluous 
If you see the flow I changed the 3 dots button for a watch later button ( to keep an experience like youtube )

**Comment by pedrocasa** [comment]
As Jelle Said on the #162 the 3 dots on the thumbs  ( options ) are superfluous 
If you see the flow I changed the 3 dots button for a watch later button ( to keep an experience like youtube )

**Comment by geckoslair** [comment]
ref to #216
