### ISSUE TITLE
Surrounding environment sniffing lib

### ISSUE THREAD

**Issue by geckoslair** [Paratii-Video/paratii-player#240]
As said weeks ago we need a central lib for recognize the user device.
The reasons are many: video fallbacks, ui fix, etc.

1. user agent regex matching OS -> http://detectmobilebrowsers.com/ ( controversial approach because has to be mantained and updated)
2. user agent "mobi" matching -> as suggested by https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent (personally the best approach)
3. check if the device is touch enable 
4. check if the device window has an orientation
5. ask to the user :stuck_out_tongue: 

a mix of all of the approaches? i'd like to have @jellegerbrandy and @ya7ya opinions

**Comment by jrgarou** [comment]
Set stats classes on the `.main-app` will be really handfull.
Something like that:

`<div id="player-fullscreen-container" class="main-app playlists in-embed in-fullscreen is-mobile is-android">`

Maybe some global status for JS. Getting the informations once, saving its and update when it need. Something like this:
```
var GLOBALS = {
  hasTouch: false,
  hasVideo: true,
  isMobile: false,
  isAndroid: false,
  isChrome: false,
  isFirefox: false,
  isSafari: false,
  inEmbed: true,
  inFullscreen: true,
  language: 'br',
  ...
}
```

**Comment by geckoslair** [comment]
@jrgarou yes i was thinking something like that, great! 
i'll try to expose some basic functions to share with you, as:

- Sniffer.getUserParamsClasses() -> return a list of classes
- Sniffer.getUserParamsObject() -> return a js object

**Comment by jellegerbrandy** [comment]
is there not some lib on npm that we can use, instead of inventing our own?

**Comment by ya7ya** [comment]
@jellegerbrandy Yes there are a few libraries. here is a couple we can try
https://www.npmjs.com/package/mobile-detect
https://www.npmjs.com/package/sniffr

**Comment by geckoslair** [comment]
@jrgarou hi man!
i've pushed on dev the new helper. Now i'm adding to the body class the following classes:

  this.classes += (this.isMobile()) ? 'mobile ' : ''
  this.classes += (this.isPhone()) ? 'phone ' : ''
  this.classes += (this.isTablet()) ? 'tablet ' : ''

You can play with them as you prefer, if no class is provided so is desktop. Let me now.

**Comment by jellegerbrandy** [comment]
@geckoslair , can i close this issue?

**Comment by geckoslair** [comment]
added isEmbedded support and closed
