### ISSUE TITLE
define a `showAlert` and `closeAlert` functions

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#244]
On the basis fo this: https://github.com/Paratii-Video/paratii-player/wiki/Code#warnings-and-alerts

**Comment by jellegerbrandy** [comment]
This issue also includes refactoring of existing code

**Comment by eliawk** [comment]
@jellegerbrandy my proposal is to create 2 components: one for modalAlert and one to manage the globalAlert (now they are the same component, passing options to them)

**Comment by jellegerbrandy** [comment]
also this: https://github.com/Paratii-Video/paratii-player/commit/379dffc5e162be3e7bdb4494adffa5f0ad997a42

**Comment by eliawk** [comment]
now there is a `showModalAlert` - `hideModalAlert` and `showGlobalAlert` - `hideGlobalAlert`
