### ISSUE TITLE
Add Tests for new profile functionality (and polish UI)

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-player#250]
#241 implements some new functionality in the the profile page, in addition to temporarily disabling some pieces (in accordance with #164).

- New tests need to be written for this new functionality, specifically regarding the new modals for changing your password or editing your avatar/username/email address.
- the profile page should match the grid alignment shown below. It is close now but there may be an opportunity to polish.
- Refactor page header styles (mostly padding) and move them to  [/internals](https://github.com/Paratii-Video/paratii-player/tree/209-profile-page/imports/ui/stylesheets/internals). They  can go into [/internals/main.less](https://github.com/Paratii-Video/paratii-player/blob/209-profile-page/imports/ui/stylesheets/internals/main.less#L6-L34) or a new `header.less`.

**Comment by jellegerbrandy** [comment]
Just copying this code comment of @bent0b0x to remind us that also this needs to be tested: 

> Steps:
> 
> user attempts to edit email
> enters an email that is already taken by another user
> Expected:
> 
> user sees an error message and has to retry
> Actual:
> 
> no error message, and user's email is deleted and leaves the account with no emails
>

**Comment by bent0b0x** [comment]
![image](https://user-images.githubusercontent.com/7697924/32665161-6817c8a2-c601-11e7-8f17-47eaa5a359d7.png)

![image](https://user-images.githubusercontent.com/7697924/32665167-6c7972c4-c601-11e7-9787-0f6022739646.png)

**Comment by eliawk** [comment]
On the profile page if you are logged in and you don't have a keystore when you close the modal you see this now 

<img width="1425" alt="schermata 2017-11-14 alle 16 13 21" src="https://user-images.githubusercontent.com/362016/32787495-f1cb733e-c956-11e7-89ae-3b3cbad91317.png">

**Comment by bent0b0x** [comment]
> On the profile page if you are logged in and you don't have a keystore when you close the modal you see this now

 @pedrocasa I don't think this case (screenshot above :point_up:) was accounted for in the profile redesign. Is this simply a feature/view we are disabling for now? If the user does not have a keystore when they log in, what should we show?

**Comment by jellegerbrandy** [comment]
If the user does not have a keystore when they login, they see a dialog screen where they get the choice of either restoring the keystore (with their keyphrase) or create a new keystore. This modal should be blocking (and perhaps is already so) - so the situation should simply not occur.

**Comment by bent0b0x** [comment]
I assume you are talking about this modal?

![image](https://user-images.githubusercontent.com/7697924/32868271-6082c73a-ca3f-11e7-85e2-3ac72ec2aaf0.png)

Currently, this modal displays after the user has successfully logged in. However, the user can dismiss it. Do we want to make this modal non-dismissible? Also, as you maybe can see from the screens, there seem to be some issues with the rendering of this modal (e.g. some of the contents are getting cut off and it is not scrollable)

![keystore](https://user-images.githubusercontent.com/7697924/32868330-bfe2453e-ca3f-11e7-8a4f-37118bedafa3.gif)

**Comment by jellegerbrandy** [comment]
+1 for making it blocking.

Not sure what we should show on the profile page here (i.e. in the background of the modal) - it could even be a blank page...

**Comment by jellegerbrandy** [comment]
Closing this generic issue (it seems to me many tests are there,b ut feel free to reopon, @bent0b0x ) - opened a new issue for the restorekystore modal #276
