### ISSUE TITLE
Add email validation on "edit Profile"

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#251]
These "xxx" email is accepted:

![image](https://user-images.githubusercontent.com/1306173/32654354-313e1872-c60b-11e7-9e29-34f83c8d3ea2.png)

**Comment by bent0b0x** [comment]
Also on this note, are there plans to require users to confirm their email address? Otherwise what mechanism do we have against users signing up w/ someone else's email, or a fake email (if this is something we need to care about)?

**Comment by jellegerbrandy** [comment]
We've been discussing informally about email handling and confirmation. At the moment, the plan is that at the moment of inscription, we only check formal correctness (i.e. it must be a valid email address). 

We will then ask users to confirm their email address in exchange for  a gift of PTI. 

Issue #248 is relevant here, but I should really write a separate issue documenting this.

**Comment by jellegerbrandy** [comment]
thanks!
