### ISSUE TITLE
Order of texts is confusing on register modal

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#258]
![image](https://user-images.githubusercontent.com/1306173/32719492-dd033212-c860-11e7-8e37-efe4971fd386.png)

I think the text "If you already have an account sign in" should become _below_ the sign up button (or at the top of the form), not in the middel fo the form (the input and submit fields should preferably be "together", not interrupted with links going elsewhere)

**Comment by pedrocasa** [comment]
There's no reason to show "if you already have account" sentence. This modal is only available after the player shows the Sign in/Sign up options ( we don't need to ask it again )

**Comment by pedrocasa** [comment]
There's no reason to show "if you already have account" sentence. This modal is only available after the player shows the Sign in/Sign up options ( we don't need to ask it again )

**Comment by eliawk** [comment]
This is done with Metor.Accounts and i think we can't disable using the config, so maybe we could juts hide it using css:
```
.at-signin-link
  display: none
```

**Comment by jellegerbrandy** [comment]
Ok, letś do that

**Comment by jellegerbrandy** [comment]
Ok, this now depends on #320

**Comment by eliawk** [comment]
This is now in #320
