### ISSUE TITLE
Edit password should change the password of the keystore

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#259]
The following is a bug in `editPassword.js`.

We must hook up here the "change the password and regenerate the keystore" logic that is in `wallet.js`.

```
    Accounts.changePassword(
      target['current-password'].value,
      target['new-password'].value,
      function (e) {
        if (e) {
          templateInstance.errorMessage.set('Current password is incorrect')
        } else {
          templateInstance.errorMessage.set('')
          hideModal()
        }
      }
    )
```

**Comment by jellegerbrandy** [comment]
assigned this to @eliawk (but @bent0b0x  should be aware of this as well)

**Comment by eliawk** [comment]
@jelle change the password and regenerate the keystore, it means if you login on an older device you can't open the old **keystore** (encrypted with the old password). so the "change password" maybe needs also a button to **regenerate** (remove + create new) keystore.

**Comment by jellegerbrandy** [comment]
Yes, we need the functionality to regenerate the keystore. But that is probably somethign that should happen on the "insert yr password here" screens, after "forgot password". 

We need some use cases, here, I think.

I want to move, eventually, to the situation described in https://github.com/Paratii-Video/paratii-player/issues/248 - which also is relevant here.
