### ISSUE TITLE
Change the layout of restoreKeystore modal

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-player#263]
The **restoreKeystore** is the only modal with buttons and looks a little bit broken

<img width="373" alt="schermata 2017-11-14 alle 10 17 53" src="https://user-images.githubusercontent.com/362016/32772107-20a40310-c925-11e7-9509-f6e00a909cbf.png">

**Comment by jrgarou** [comment]
@geckoslair Done https://github.com/Paratii-Video/paratii-player/commit/be85ba17d3f29db5e8f71787e7141fcc1245407f
