### ISSUE TITLE
Form placeholder text color is too dark

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-player#273]
The placeholder text for sign in/sign up/edit profile is the incorrect color. It is the same color as the actual text the user types, which is confusing.

![image](https://user-images.githubusercontent.com/7697924/32928679-3560ea22-cb21-11e7-8a53-af330819fa74.png)

The actual color should be `@color-light-grey`

**Comment by pedrocasa** [comment]
We should use the light grey for the description and the darker grey for the typed form 

@jrgarou

**Comment by bent0b0x** [comment]
@pedrocasa 

Here is an example with the dark gray for the typed text ("Ben Baum") and the light gray for the placeholder ("fffffobar@gmail.com")

![image](https://user-images.githubusercontent.com/7697924/32931177-c8aaba56-cb30-11e7-8631-71769a398b38.png)

In my opinion, the difference is still too subtle, at least for this use case. Looks like the light grey color was recently updated to be darker, but not sure if it works great here. Let me know what you think!

**Comment by pedrocasa** [comment]
the grey colours has no contrast on the Roboto light font as the player needs 

- Changing the dark grey for a darker colour will make the whole player visually heavier
- Changing the light grey for a lighter colour will make the forms hard to read

we have two options 
Or we can change the font weight to medium when the user is writing ( still same colour )  ... or we can create a new darker colour that is used just for this specific moment.

In my opinion, the first option works fine to me ( simpler solution and a fine result )

![image](https://user-images.githubusercontent.com/30123644/32945373-4352d434-cb7a-11e7-8598-f318cd12292a.png)

**Comment by pedrocasa** [comment]
@jrgarou  tell me what u think about it

**Comment by jrgarou** [comment]
Hey @bent0b0x, good point. This need to be fixed. 
All styles from our forms elements is in here: https://github.com/Paratii-Video/paratii-player/blob/frontend/imports/ui/stylesheets/components/forms/main.less

We can fix this here https://github.com/Paratii-Video/paratii-player/blob/frontend/imports/ui/stylesheets/components/forms/main.less#L72-L128

Could you take this for me?
