### ISSUE TITLE
Restore keystore modal needs layouting

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#276]
[moved thsi comment from @bent0b0x from #250 to a new issue:]

![image](https://user-images.githubusercontent.com/7697924/32868271-6082c73a-ca3f-11e7-85e2-3ac72ec2aaf0.png)

Currently, this modal displays after the user has successfully logged in. However, the user can dismiss it. Do we want to make this modal non-dismissible? Also, as you maybe can see from the screens, there seem to be some issues with the rendering of this modal (e.g. some of the contents are getting cut off and it is not scrollable)

![keystore](https://user-images.githubusercontent.com/7697924/32868330-bfe2453e-ca3f-11e7-8a4f-37118bedafa3.gif)

**Comment by jellegerbrandy** [comment]
+1 for making it blocking.

the background here (i.e. the "restore wallet" stuff on the actual profiel page behind the modal) can be simply removed (we can show a blank page)

**Comment by eliawk** [comment]
@jellegerbrandy the modal has now a new layout

<img width="350" alt="schermata 2017-11-20 alle 13 19 54" src="https://user-images.githubusercontent.com/362016/33018152-88c08002-cdf5-11e7-99b5-b5ba1260d529.png">

but is not blocking. wha we do?

**Comment by jellegerbrandy** [comment]
make it blocking :-)

**Comment by eliawk** [comment]
@jellegerbrandy done
