### ISSUE TITLE
Found a user Keystore

### ISSUE THREAD

**Issue by geckoslair** [Paratii-Video/paratii-player#278]
keep the user's choice without re-opening the modal

**Comment by eliawk** [comment]
@geckoslair keep the user choice in the session or permanently in the local storage?

**Comment by geckoslair** [comment]
local storage @eliawk

**Comment by jellegerbrandy** [comment]
Now using sessionStorage. Do we want to change that? who's the owner here, @geckoslair  or @eliawk ? 
Moving to doing for now.
