### ISSUE TITLE
Limit the amount of tags/keywords to be shown on the player

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#282]
We can just show 3 keywords (or even not show them at all, given that they are not working yet)

![image](https://user-images.githubusercontent.com/1306173/32944556-3c8432cc-cb90-11e7-9033-79925d95a3ec.png)

**Comment by geckoslair** [comment]
maybe we can group after N tags like:
tag1, tag2, tag3, [button] see more tags [/button]

**Comment by jellegerbrandy** [comment]
i say we just show the first 4 tags and that's it (we can use the rest for search)
or even not show them at all - we can surely use the real estate - what do you say @pedrocasa ?

**Comment by jellegerbrandy** [comment]
Ok, so shall we just remove the tags? They are ugly and non-functional.

**Comment by eliawk** [comment]
@jellegerbrandy temporary removed the tags
