### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-player#284]
Me and Junior are working on some changes on the thumbnails ... There will be no more "boxes-under pictures titles " just a title above the picture and an overlay layer.

![001](https://user-images.githubusercontent.com/30123644/32949228-38898bd8-cb89-11e7-9615-6007e99ca5f0.png)

We found a small problem, the images that are automatically created for the thumbnails all have black horizontal lines as if it had a different aspect ratio than the box they're in. ( images below )

![002](https://user-images.githubusercontent.com/30123644/32949339-a3a2ed4c-cb89-11e7-8e51-03c20e213b44.png)

![image](https://user-images.githubusercontent.com/30123644/32949253-584f5d8a-cb89-11e7-96bd-48ca66e957d1.png)

**Comment by jellegerbrandy** [comment]
@ya7ya

**Comment by ya7ya** [comment]
@jellegerbrandy  Regarding the Thumbnails, the youtube videos thumbs are made by youtube. I'll check to make sure it generates in a better aspect ratio.

Whats the optimum required screenshot aspect ratio ?? @pedrocasa

**Comment by eliawk** [comment]
@pedrocasa @jrgarou if you use image as backgroun image instaed of `<img>` tag? so you could manage the aspect ratio a little bit more easily using the padding-top trick..could be?

**Comment by pedrocasa** [comment]
@ya7ya  I think 5x3 is fine
