### ISSUE TITLE
Give feedback on unsuccessful searches

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-player#292]
### Description:

When users search for something and there's matches, results come up. When there's no match, nothing shows up and we stare at blank.

#### Steps to Reproduce:

  1. Just go to "search" and search something.
  
#### Actual result:

https://media.giphy.com/media/xUOxeQzE3ZFKFJ5skM/giphy.gif

#### Expected result:

Our standardised text format/colour saying: "Want to try different keywords?"
**Suggestion**: A "cool text" along the lines & graphic direction @pedrocasa propopses for https://github.com/Paratii-Video/paratii-player/issues/154, here, displaying "The truth is not for all, but only for those who seek it." - Ayn Raid (feel free to ignore)

**Comment by jrgarou** [comment]
@jellegerbrandy @geckoslair @eliawk 
How the search query is working?
Looks like it brings results only when a whole word is typed.

- Typing 3 characters from a existing video title
![image](https://user-images.githubusercontent.com/320157/33128077-3ac4ad1e-cf72-11e7-8ca5-3dc085c6f9f1.png)

- Typing the whole word
![image](https://user-images.githubusercontent.com/320157/33128204-b38de4ea-cf72-11e7-8680-30bca7889e09.png)

- Removing just 1 character no results is showed
![image](https://user-images.githubusercontent.com/320157/33128249-d561f44e-cf72-11e7-8c65-242efc126a95.png)

- Using only 2017 it brings another result
![image](https://user-images.githubusercontent.com/320157/33128282-f946b9d0-cf72-11e7-81e1-cab7565a28e2.png)

**Comment by geckoslair** [comment]
fixed in a906ec6 !

**Comment by felipegaucho** [comment]
Hi @geckoslair, I still search for CES on staging and get no results, until I type CESC2017:

<img width="637" alt="screen shot 2017-11-24 at 10 58 27 am" src="https://user-images.githubusercontent.com/26517120/33211664-a42b1fe6-d106-11e7-8aed-eb40f1568b07.png">

**Comment by geckoslair** [comment]
misunderstand the issue, reopening

**Comment by geckoslair** [comment]
closing in favour of #324
