### ISSUE TITLE
"Buy Video" slider appears briefly (empty) on all videos before vanishing

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-player#296]
### Description:

In every video, the purple "buy Video" slider appears briefly. It then disappears on free videos. It blinks.

#### Steps to Reproduce:

  1. Just open any video and notice near the upvotes/downvotes.

#### Actual result:

![giphy 3](https://user-images.githubusercontent.com/26517120/33077224-60379604-ceb6-11e7-8f1f-8a7224cb34c1.gif)

#### Expected result:

This blinking doesn't happen :)

#### Specifications and/or additional information

I'm on Chrome, btw.

**Comment by geckoslair** [comment]
@felipegaucho let's check once deployed on staging
