### ISSUE TITLE
Show "..." for long video titles, in the thumbnail preview

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-player#298]
### Description:

Video titles that are too long get cut abruptly on the thumb preview.

#### Steps to Reproduce:

  1. Just to go any playlist.
  
#### Actual result:

<img width="377" alt="screen shot 2017-11-21 at 12 25 26 pm" src="https://user-images.githubusercontent.com/26517120/33077487-1a5ffe7c-ceb7-11e7-9ccc-1b3da0ae07c3.png">

#### Expected result:

There's a "..." at the end, or other solution along these lines?

**Comment by pedrocasa** [comment]
It should be "..." 
If you take a look on my design I have already projected these long titles with the three dots

**Comment by jellegerbrandy** [comment]
@pedrocasa : can you give the refence to yr design?

* Making cuts at the right point is difficult - because the length of the text depends on the font used, so we cannot just count chars ( (WWWWWWW will not fit, IIIIIII will). So let's not do that

* solution 1: use css ellipsis: https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_js_text-overflow
* solution 2: use CSS, put title in a box with a fixed height, set overflow hidden (this is what youtube does)

I personally prefer 2. (solution 1 will put the ellipsis also in the middle of a wor...)

**Comment by pedrocasa** [comment]
I designed it with the three dots because I saw youtube using it 

![capture](https://user-images.githubusercontent.com/30123644/33267479-cb5f6ad4-d360-11e7-9bfc-1a3e552f64db.JPG)

**Comment by pedrocasa** [comment]
![capture](https://user-images.githubusercontent.com/30123644/33267523-f67dd660-d360-11e7-8d73-b8b75f2edb6b.JPG)

**Comment by jellegerbrandy** [comment]
So YT does both :-) (I was lookig at the titles on the youtube page)

Cutting the text on whole words (as in your design) and adding ellipsis is a bit tricky in javascript. Also, with such a small space, the three dots occupy space that is probably more useful if occupeid by three more letters of the title. I still vote for (2)

**Comment by eliawk** [comment]
@pedrocasa @jellegerbrandy @felipegaucho i fix this with css ellipsis and it looks good.
Maybe we would consider to make a pagination of 4 instead of 6 to have bigger previews?
but this will be an other issue..

**Comment by jrgarou** [comment]
Not just in this thumbnails case, but we could truncate with ellipsis all **one single line** texts using css.
And for multiples lines texts we can hide with `max-height` + `overflow: hidden` and use ellipsis for browsers with support: https://caniuse.com/#feat=css-line-clamp

 #### One line is fine for thumbs title?

**Comment by felipegaucho** [comment]
I think few/no players go for 2 lines. More space in this case is a matter of thumb size.
