### ISSUE TITLE
Registration UX Issues

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-player#300]
1. When the user attempts to sign up w/ an email that is already taken, the error message shoves other UI elements into each other

![signupbug](https://user-images.githubusercontent.com/7697924/33080015-094ebd2e-cea5-11e7-9461-ca6c27d9f269.gif)

***

2. After an unsuccessful signup, and the user dismisses the register modal, when they open it back up again their previous error message (if any) is still rendered.

![signupbug2](https://user-images.githubusercontent.com/7697924/33080105-44e77312-cea5-11e7-9ae6-0b217d822551.gif)

**Comment by pedrocasa** [comment]
Ben take a look at https://github.com/Paratii-Video/paratii-player/issues/169

@jrgarou  are gonna help u to find those error boxes

**Comment by bent0b0x** [comment]
@jrgarou maybe you already have a plan for this, but as far as I can tell we do not have great control over the modal for the sign-in/sign-up process. Looks like `atForm` takes care of all of this for us. Should we, however, use our own template so we gain more control (which might be useful in cases like this where we want to control how errors are displayed)?.

**Comment by jrgarou** [comment]
@bent0b0x I totally agree with you. 
The problem with `atForm` is we ain't got control(until I know) on template and classes, template changes and template updates. So is hard to apply the same transition from our `embedCustomizer`, for example.

There's some features that `atForm` takes care for us. So for now(@jellegerbrandy could talk better about it) we decide to not change that.

But, I did develop(style, transitions, template changes and template updates) of modals designed by @pedrocasa - including this sign in/up/recover/confirm steps.

**Comment by jellegerbrandy** [comment]
Yes, also talked about htis yesterday with @eliawk 

Let's get rid of the shitty atForm modals after all.

Retrospectively it was a bad decision to keep them (.... I know ... )

I've made a new issue for that, #320. This issue depends on that.

**Comment by bent0b0x** [comment]
@eliawk are you taking care of both of these problems in your branch? Just making sure so I do not do any work on an alternate solution!

**Comment by jellegerbrandy** [comment]
He @bent0b0x , yes, lets wait with this issue until Elia's refactoring is done (he's away for a few days but enrico is workign on it now)

**Comment by jellegerbrandy** [comment]
Refactoring is (mostly) done, we now have a form like all the others. Moving from waiting to todo

**Comment by bent0b0x** [comment]
I'm going to close this; resolved by @eliawk and @enricocicconi's changes!
