### ISSUE TITLE
Search pagination boundaries

### ISSUE THREAD

**Issue by geckoslair** [Paratii-Video/paratii-player#303]
I need help to manage pagination boundaries in search results.
In playlist pagination it's easy because i know the length of videos.

Ideas?

**Comment by geckoslair** [comment]
ref #260

**Comment by jellegerbrandy** [comment]
I'm not sure what you mean, @geckoslair ?

**Comment by geckoslair** [comment]
@jellegerbrandy 

**Playlists videos** and **search results** have pagination.
Each list need controllers for hasNextPage hasPrevPage, i call these controller "boundaries".

**Playlists videos** the controller (already implemented) it's easy because i know the total items within the playlist (it's an array inside the playlist).

**Search results** it's hard because i'm subscribing to a pubblication passing the current page. I miss the total items number.

Known options:

- [ ] make a second call in order to get the total items number
- [ ] remove boundaries ( mainly hasNextPage). If the user click the next button and there are no results provide a message like "no results"
- [ ] remove pagination for search results in favour of a kind of infinite scroll.
