### ISSUE TITLE
Email sharing has no feedback

### ISSUE THREAD

**Issue by geckoslair** [Paratii-Video/paratii-player#312]
### Description:

Sharing via email gives no feedback after email is sent

#### Steps to Reproduce:

- https://staging.paratii.video/play/QmQNmx5C6YpbP5KtWiB3wHB8Cz2UpBA1RLa31emCs1Z54m?playlist=2

- share

- via email

- enter a email address

- send
  
#### Actual result:

- on success back to sharing choices
- no feedback

#### Expected result:

- on success back to sharing choices
- feedback

#### Specifications and/or additional information

- recipient email need to be in whitelist, ask @enricocicconi

**Comment by geckoslair** [comment]
ref: #313

**Comment by jrgarou** [comment]
@pedrocasa What you think about this situation:
- on success back to sharing choices
- feedback with success alert

![image](https://user-images.githubusercontent.com/320157/33555914-4246fb20-d8e9-11e7-8d0b-979c846470ee.png)

**Comment by geckoslair** [comment]
wait for merging and deploy

**Comment by jrgarou** [comment]
@geckoslair I create a pullrequest https://github.com/Paratii-Video/paratii-player/pull/367 with this
