### ISSUE TITLE
Fullscreen mode should be toggle doubleclicking on the video

### ISSUE THREAD

**Issue by geckoslair** [Paratii-Video/paratii-player#314]
fairly widespread behavior

**Comment by eliawk** [comment]
@geckoslair is this already available with clappr integration?

**Comment by bent0b0x** [comment]
Is this expected behavior? I would think that clicking on the video merely plays/pauses (which is how it works on YouTube). What is an example where a double click takes a video full screen?

**Comment by bent0b0x** [comment]
We likely want to also include single clicks playing and pausing the video as well; I believe this is fairly universal

**Comment by bent0b0x** [comment]
Took a stab at this in #361

**Comment by geckoslair** [comment]
we can close it! 
@eliawk maybe, but @bent0b0x has wrote tests for it, so if tests will fail we will integrate the feature also for clappr :+1:
