### ISSUE TITLE
Player controls are partially hidden on Twitter timeline

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-player#318]
### Description:

Controls of the player get hidden on Twitter timeline. When we click on the "tweet card" and it expands, the player dimensions are fine.

#### Steps to Reproduce:

  1. Just share a video (trying from staging here) on Twitter. The "phrase attached" thing is super fun BTW :)
  2. Then see it on the timeline, and try to play it.
  
#### Actual result:

<img width="361" alt="screen shot 2017-11-24 at 11 06 14 am" src="https://user-images.githubusercontent.com/26517120/33211963-163d2984-d108-11e7-85ed-28d681478a6a.png">

Or even worse, if there's too many tags, the controls might even be completely hidden:

<img width="354" alt="screen shot 2017-11-24 at 11 07 00 am" src="https://user-images.githubusercontent.com/26517120/33212043-62d57c9c-d108-11e7-94d6-bf942acf11eb.png">

#### Expected result:

The same as you get when you click on the card and expand it:

<img width="364" alt="screen shot 2017-11-24 at 11 06 38 am" src="https://user-images.githubusercontent.com/26517120/33212055-6ead9ebe-d108-11e7-8d9c-6fe90eace1cb.png">

**Comment by jellegerbrandy** [comment]
related to the #282 (where i've proposed to remove the tags)

For the title, there are two options (we can combine them):
- make the font smaller when the title is longer
- cut off the font with an ellipsis (with 3 dots)

I vote for the second.

@pedrocasa , what do you think?

**Comment by felipegaucho** [comment]
For the record (after talking w/ @pedrocasa): we'll use the 3 dots; tags won't show up in the twitter-sized version; in larger versions tags will appear "hidden at first", along the description, and will be limited to ~4 (to be shown).

**Comment by pedrocasa** [comment]
https://github.com/Paratii-Video/paratii-player/issues/332

**Comment by pedrocasa** [comment]
We should use a new dimension for the player fits on twitter ( 490X280)

**Comment by geckoslair** [comment]
we need @jrgarou magic!

**Comment by eliawk** [comment]
@jrgarou just for the records i've removed the tags from the player because atm they are useless (there is no link, navigation) they are just keywords. if you have a different idea you just need to delete the pull request with the changes
