### ISSUE TITLE
Remove atForm  dependency

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#320]
The login and register modals are based on atForm. That makes them really difficult to style. 
We can use native forms. 

(The reason was that we had difficulties getting custom forms to work nicely with the register process of meteor -- so whoever takes up this issue is invited to start there first :-)

**Comment by eliawk** [comment]
i've done a lot of work in the new branch: https://github.com/Paratii-Video/paratii-player/tree/new-login, but test are failing beacuse they can't see the seed in the modal (even if it's there)

<img width="436" alt="schermata 2017-11-24 alle 19 27 26" src="https://user-images.githubusercontent.com/362016/33221114-8555525c-d14d-11e7-8d67-cf92bb1238fb.png">

**Comment by eliawk** [comment]
@jellegerbrandy do you have any idea about it?

**Comment by bent0b0x** [comment]
@eliawk I tried running this locally and I think the problematic lines are in fact [these](https://github.com/Paratii-Video/paratii-player/blob/new-login/tests/profile.test.js#L56-L59), as well as [this assertion](https://github.com/Paratii-Video/paratii-player/blob/new-login/tests/profile.test.js#L72). If they are commented out the test "passes".

So it would seem that for some reason the login flow on this branch is not logging in correctly as far as meteor is concerned? Not sure, didn't dig into it any farther than that.

**Comment by eliawk** [comment]
@bent0b0x thanks for your check. the application work (login an register), but (old) test are not passing. the problem it's in the test? or maybe the code has some issues..

**Comment by geckoslair** [comment]
@bent0b0x @eliawk fixed in 88cc5a1874a4926da736384013088168d5522342 ,
i don't know if the issue is close

**Comment by jellegerbrandy** [comment]
OK @jrgarou, you'll be happy to kow we got rid of the atForms, finally. I merged the changes.

Very happy :-)

**Comment by jrgarou** [comment]
Not yet, @jellegerbrandy 
@geckoslair @eliawk could we remove(not import) all bootstrap css from app?

**Comment by eliawk** [comment]
@jrgarou 

> all bootstrap css from app?

you mean bootstrap for the login or for the application?
in the second case i will open an other issue and close this one

**Comment by jellegerbrandy** [comment]
I don't have a strong opinion about bootstrap yes/no (just want to point out that our Modals also use bootstrap javascript). In any case, I think a new issue for that is appropriate.

What I was wondering though, @eliawk , before closing the issue: did you also remove the meteor package?

**Comment by eliawk** [comment]
@jellegerbrandy yes i removed the package, now there are just `accounts-base` and `accounts-password`

**Comment by jellegerbrandy** [comment]
++++++1
