### ISSUE TITLE
Search works just if match keyword perfectly, we want something flexible 

### ISSUE THREAD

**Issue by geckoslair** [Paratii-Video/paratii-player#324]
ref: #292

**Comment by jrgarou** [comment]
@enricocicconi the `showPagination` returns _true_ when the `keywords` from search wasn't _undefined_: https://github.com/Paratii-Video/paratii-player/blob/dev/imports/ui/pages/search/search.js#L94

Could we just show the pagination when `videos.length > Meteor.settings.public.paginationStep` or something like that?


The [video.fetch](https://github.com/Paratii-Video/paratii-player/blob/dev/imports/ui/pages/search/search.js#L82)  returns 6 paged videos and [totalVideos](https://github.com/Paratii-Video/paratii-player/blob/dev/imports/ui/pages/search/search.js#L18) always return _undefined_.

**Comment by geckoslair** [comment]
Hi @jrgarou! Can you create a new issue? This is about keyword matching.
BTW, yes!

**Comment by jellegerbrandy** [comment]
Use a regexp matched to the beginning of the word. According to this:https://stackoverflow.com/questions/3305561/how-to-query-mongodb-with-like

something liek this shoudl work:

    db.users.find({"name": /m.*/})

**Comment by geckoslair** [comment]
@jellegerbrandy 
from what I've understood in order to have score system we need to use the $search sintax.
but $search syntax support just string and not regex.

**Comment by jellegerbrandy** [comment]
Ah yes. Well. We have 50 vids. Lets thunk about scoring once we have 10000

**Comment by geckoslair** [comment]
waiting for deploy

**Comment by geckoslair** [comment]
deployed
