### ISSUE TITLE
Give an indication, on the wallet, of why the user has no $

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-player#329]
### Description:

This is something that has been discussed w/ @pedrocasa: on the wallet there's 0 funds and things are fine, but we can just say "it's not your fault there's no money here, it's just that this is still a demo" + a fun icon for an error, alert, or something. It can be something simple since it'll be temporary. There's some empty space that could be filled (see below).

<img width="1004" alt="screen shot 2017-11-26 at 10 01 44 am" src="https://user-images.githubusercontent.com/26517120/33240262-9e68a372-d29a-11e7-8118-89273c9cf519.png">
<img width="611" alt="screen shot 2017-11-26 at 9 36 20 am" src="https://user-images.githubusercontent.com/26517120/33240263-9fa9e638-d29a-11e7-9809-3943307223b8.png">

**Comment by pedrocasa** [comment]
We should  use the same alerts as https://github.com/Paratii-Video/paratii-player/issues/169

@bent0b0x  @jrgarou

**Comment by pedrocasa** [comment]
![capture](https://user-images.githubusercontent.com/30123644/33269917-717c2cec-d369-11e7-8808-4274beee8022.JPG)

**Comment by pedrocasa** [comment]
![capture](https://user-images.githubusercontent.com/30123644/33269964-96b2a568-d369-11e7-884d-cd78c6915e47.JPG)

**Comment by felipegaucho** [comment]
@pedrocasa , registering the feedback from the call: let's make it not like an alert, but rather as actual text inside the page. Either under or to the side...

**Comment by eliawk** [comment]
@pedrocasa @felipegaucho so let me know how you want to change this message. for the instance it has been merge as modal like in the design

**Comment by jellegerbrandy** [comment]
![image](https://user-images.githubusercontent.com/1306173/33485339-5a982536-d6a6-11e7-8329-56e9fe2fd1f3.png)
