### ISSUE TITLE
Design.MiniTwitter. purchase flow ( MT01-MT21)

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-player#332]
I have made a new purchase flow that can help us with some troubles that we are having with the twitter dimensional problem.

- I have renumbered all the pages to don't confuse with the older flows
- Please if you wanna talk about an especific page write the number

![novo_flow](https://user-images.githubusercontent.com/30123644/33286744-7725923a-d39d-11e7-87b2-3dad00da6d27.png)

**Comment by jellegerbrandy** [comment]
Does this replace the earlier "mini" designs?

**Comment by pedrocasa** [comment]
it has the same objective as the Mini, just in a new dimension.

So yes, it kind of replaces it ... When I uploaded it I didn't know if I should give a new name or use the same as before

**Comment by jellegerbrandy** [comment]
Perhaps you can close the  issues with the earlier versions, so we do not get confused.

**Comment by jellegerbrandy** [comment]
Question: so according to the break points defined in felipes comment on #116 , shoudl Twitter ( 490X280) not show the "tiny" mode?

**Comment by pedrocasa** [comment]
Oh, I thought it was already closed, my bad ( closed now )

well remembered, I have changed the defined breakpoints for the MINI version on felipes comment

**Comment by jellegerbrandy** [comment]
I moved the breakpoint documentation to the wiki: https://github.com/Paratii-Video/paratii-player/wiki/Breakpoints

**Comment by felipegaucho** [comment]
Also, @pedrocasa, didn't we decide to hide the tags with the description?! Why do we need the options "wheel" on the top right in these cases?

**Comment by pedrocasa** [comment]
tags corrected
