### ISSUE TITLE
Infinite return to a page using backButton

### ISSUE THREAD

**Issue by jrgarou** [Paratii-Video/paratii-player#333]
When we click on backButton looks like it navigate to page instead of return to page in browser history.
So we create a loop and can't return 3 steps. If I start on a video page, go to playlists page and go to profile page the back button never return to the video.

![backbutton](https://user-images.githubusercontent.com/320157/33271644-f80b653e-d36e-11e7-80da-6f7d45496d63.gif)

**Comment by bent0b0x** [comment]
Thanks for documenting, looking at this now
