### ISSUE TITLE
Around the Block playlist is empty. Add content + thumbnail

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-player#336]
### Description:

The playlist "Around the Block" is empty. It should contain 3 videos: 
https://www.youtube.com/watch?v=BFU5JnaqaDY&index=6&list=UU5OOwdF37P_oT0OVf2DvuPg
https://www.youtube.com/watch?v=gvLXjp8QD20&index=4&list=UU5OOwdF37P_oT0OVf2DvuPg
https://www.youtube.com/watch?v=LR1fOVVxqZU&index=3&list=UU5OOwdF37P_oT0OVf2DvuPg

#### Steps to Reproduce:

https://player.paratii.video/playlists/5

Let's also use thumb from the videos (I suppose we have a placeholder 'cause the playlist is empty)

**Comment by ya7ya** [comment]
@jellegerbrandy I added the missing videos for around the block series to the fixtures. https://github.com/Paratii-Video/devops/pull/23
