### ISSUE TITLE
check for @watch statements in precommit handler

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#344]
We should refuse to commit changes that include `@watch` statements in the test.

 it shoudl happen pre-commit together with the `lint` command. 

Not sure how to best handle this. Can the linter be configured to do it?

**Comment by geckoslair** [comment]
@jellegerbrandy utils added in 344-removeWatcher

**Comment by geckoslair** [comment]
seems to be closed. waiting for team propagation
