### ISSUE TITLE
extra 2 batches of content/playlists for 0.0.2

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-player#368]
### Description:

To upload, until uploader is WIP... See https://docs.google.com/spreadsheets/d/1EFSz_0Cunqdi31HxfjcrxRSSrlEbnuwCERbWUK9l06A/edit?usp=sharing for the links  metadata.

**Comment by jellegerbrandy** [comment]
It would be cool if we could upload them using `paratii-lib`, @ya7ya ...
