### ISSUE TITLE
Design.UploaderFlow

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-player#380]
Hey guys, 
Here is the basic flow for the uploader inside the player.
I tried to use only elements that we already got in our player to make things easy
Please tell me what you think about it and if it is what we were planning to do

![design uploader](https://user-images.githubusercontent.com/30123644/33965525-61d9a0b2-e043-11e7-80c0-abf4b0f64e6a.png)

**Comment by jrgarou** [comment]
@pedrocasa how the flow gonna happen? Are modals will open one on top of the other, resize or close/open?
Maybe all flow could be happen in one modal(size) only.

On **MT24** the "back" button label could be "Change file" or something more clear about the action.
