### ISSUE TITLE
Playlists with no videos display and are selectable

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-player#382]
I have not dug into this enough yet to know if a) empty playlists are already supposed to be hidden or b) this is a UX issue we have not yet accounted for.

![emptyplaylist](https://user-images.githubusercontent.com/7697924/33975706-5043bdfe-e05e-11e7-9285-3d0ef10570e8.gif)

If this is a UX issue we simply haven't accounted for, would like input from @pedrocasa

**Comment by bent0b0x** [comment]
[This line](https://github.com/Paratii-Video/paratii-player/blob/master/imports/ui/pages/playlists/playlists.js#L58) in `playlists.js` is likely the culprit. We retrieve all playlists w/o filtering playlists with no videos.

**Comment by jrgarou** [comment]
Something like this happens on `/search` page.
**It shows the pagination when there's nothing to paginate.** 

![image](https://user-images.githubusercontent.com/320157/33993940-d1dd73b2-e0bf-11e7-96fc-2ec446cfa0ca.png)
