### ISSUE TITLE
Player in production is not playing videos

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#389]
http://player.paratii.video/play/QmVKgd4AzrnjKFiuuXEKvfuDz1uoYGeagddrdNTmYvN2wX?playlist=1

**Comment by jellegerbrandy** [comment]
```c492be196a5dfbb11dad588c8a07e06c1e7fe899.js?meteor_js_resource=true:17 [error] > internal error happened while processing hlsManifestLoading:Cannot read property 'get' of undefined```

**Comment by jellegerbrandy** [comment]
@ya7ya , you recognize this error? Is it an easy thing to resolve?

**Comment by ya7ya** [comment]
hey @jellegerbrandy , I'm on it 👍

**Comment by ya7ya** [comment]
@jellegerbrandy I'm not seeing the same issue locally. or on staging, which makes me think it might be an issue solved by a fresh `npm install` 
working on staging : https://staging.paratii.video/play/QmVKgd4AzrnjKFiuuXEKvfuDz1uoYGeagddrdNTmYvN2wX?playlist=1
