### ISSUE TITLE
Transaction History

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#40]
This regards the list of previous transactions.

History is stored in a mongodb table called " events". (These will become ethereum Events later...)

Events have: `sender` , ` receiver` (these are ethereum accounts), ` description` , `transactionId` and `amount`, for now.

Preferably, these will be filterable and searchable on the wallet page (or, if they do not fit there for reasons of space, on a separate page)

**Comment by eliawk** [comment]
"description" = will be a field in the wallet page form?
"transactionId" = the auto id created by mongo is it good?

**Comment by jellegerbrandy** [comment]
the transaction id will be the ethereum one but for now mongo is fine. description: yes, it. may also be a field in the form, but it isostly meant fornthe micro transactions that will happen automatically and come with their own description.

**Comment by jellegerbrandy** [comment]
here is some docs about ethereum events:
http://solidity.readthedocs.io/en/latest/contracts.html#events
https://github.com/ethereum/wiki/wiki/JavaScript-API#contract-events

**Comment by jellegerbrandy** [comment]
* in first iteration: read the ether value transactions from the blockchain and show them
 * second iteration: use meteor Collections: perhaps inspired by `meteor-ethAccounts`.

**Comment by geckoslair** [comment]
i've added a primitive function in debug.js. At the moment the function scan all the blocks and look for from/to public address matches with current user public address. An improvement: Scan can be done using as startblock the last block at the moment of user registration. Transactions can be stored locally saving the latest block available, which can be use for later scan.

**Comment by jellegerbrandy** [comment]
closign this as duplicate of this new ticket that I made by accident: #66
