### ISSUE TITLE
webtorrent experiment

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#43]
Make it so that the player can play files over webtorrent.

This serves mostly as an experiment to see what the issues are.

https://webtorrent.io/

Some issues to pay attention to:

 - performance
 - UX 
  - what do we show of the p2p mechanics (see webtorrent.io, which as a nice visualization as well)
  - we can already to PTI accounting (i.e. compare upload/download totals and translate these in pti)

**Comment by felipegaucho** [comment]
We have [webtorrent operating](https://github.com/Paratii-Video/paratii-player/blob/56b598dc215c1879b95dbef9c9637785054579b6/imports/ui/pages/player/webtorrent.js). Tentative next steps are:

- [ ] Minimal "conected peers" interface (dynamic graph) appearing on a corner of the player during hover (as in [this reference](https://webtorrent.io/), much smaller).
- [ ] Number of peers / leechers, along this interface.
- [ ] Log bandwidth downloaded / uploaded in [transactions history](https://github.com/Paratii-Video/paratii-player/blob/c132263877e1e101a41e35e874386e67313741ca/imports/api/transactions.js) (using measurement units for bandwidth, for now).
- [x] Build playlist w/ only webtorrent hosted videos - 3? ([playlist](https://github.com/Paratii-Video/paratii-player/blob/666bced4cdc93b86d85deb104ae15e9d39b97386/imports/ui/pages/playlists/playlists.html) implementation logic may not yet be fully in place).
