### ISSUE TITLE
profile page

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#47]
We will have a general profile page with the following information:

 * name
 * email
 * profile image
 * account
 * pti balance
*  eth balance
 * reputation balance

and a number of actions:

  * edit profile (-> modal with edit form)
  * send pti (--> modal with amount and destination)
  * send eth (--> modal with amount and destination)
  * show 12-word key (--> modal)
  * reset password 
  * history of transactions (--> a page with searchable transaction history)

TODO:

- [x]   implement functionality of page (i.e. combine existing profile and wallet)
- [x]  create design [Paolo]
- [x] ~~Implement change password~~ 
- [x] ~~Implement reset password~~
- [x] Implement send ether
- [x] Implement send pti 
- [x] use modals instead of prompt: #38
- [x] show 12 word seed (as a modal)
- [x] if there is no keystore, option to generate or restore the keystore

**Comment by jellegerbrandy** [comment]
**change password** works like this:

 1. User clicks "change password"
 1. User is asked to provide the old password
 1. Wallet is opened and regenerated
 1. Password is changed on server

**reset password** works like this:

 1. user clicks "reset password"
 1. user is asked for the 12-word seed
 1. user is asked for new password
 1. wallet is regenerated using seed and new password
 1. password is reset on server(*)

(*) We should prove to the server that the seed corresponds to the users's ethereum account The server knows the user's ethereum account. in theory, the wallet can sign a message, send it to the serer, and the server can use that as proof. In practice (for MVP puproses, not for production) we'll just check if the new wallet generates the correct address.

**Comment by eliawk** [comment]
Could we consider it closed?
