### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#60]

**Comment by felipegaucho** [comment]
@jellegerbrandy is this up still?

**Comment by jellegerbrandy** [comment]
It is more of a UX issue. At the moment we do not have a real mechanism for asynchronous messages 

(think of: "I open dialog, click send pti, dialog closes, one minute later the app knows that the action has failed" - we have no natural place now to notify the user)

 i think we can consider it out of scope for the MVP - closing the issue; if the issue comes up when we do testing, we can re-open.

**Comment by jellegerbrandy** [comment]
We have an alert system now
