### ISSUE TITLE
wallet creation: tell user about backup and stuff

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#61]
Currently, when a new account is created, a new wallet is created "in the background". Instead, we need to show a dialog reminding hte user that

(1) REMEMBER the !#@$@#@$ keyphrase
(2) disclaimer about safety, reponsability,  that this is not an ethereum address on the ethereum blockchain at the moment

**Comment by mrocha94** [comment]
![image](https://user-images.githubusercontent.com/9802645/31916011-8456ac66-b82f-11e7-90ba-d670d9281244.png)

Is it fine?

**Comment by jellegerbrandy** [comment]
Yes, pretty good, thanks. I think we will adapt the copy once we have it integrated.
