### ISSUE TITLE
keystore needs to be saved corresponding to userId

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#63]
the scenario that needs to work is:

 - login with account A
 - use keystore of account A
 - logout
 -login iwth account B
 - use keystore of account B

**Comment by geckoslair** [comment]
@jellegerbrandy  what about actual feature?
road 1: we provide a migration from previous implementation
road 2: we just change the way we save the keystore, everybody will create a new keystore

**Comment by jellegerbrandy** [comment]
ok pretty cool. About the "upgrade" path, can do a 3rd road like this:

    ks = localstorge.get('keystore-{userid}')
    if (ks == null) {
        ks = localstorage.get('keystore')
    }

so its backwards compatible?

**Comment by geckoslair** [comment]
@jellegerbrandy what about ask team to save their seed and use it in order to recover wallet =) ?
