### ISSUE TITLE
wallet is not handled well if new acccount creation fails

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#79]
to reproduce:
 * logout your account
 * try to register a new account with the same email, it will fail
 
first bug: a modal with a seed will be showed
 * login with your usual account

second bug: the address will be wrong
 * refresh the page and the address will be correct

**Comment by mrocha94** [comment]
As described in 9e31bb7, it is not the best solution for the problem. Maybe a refactoring of [createKeystore](https://github.com/Paratii-Video/paratii-player/blob/9e31bb7304ae29b6a2b31d494c4639b86950a0e7/imports/lib/ethereum/wallet.js#L19) can help to resolve it.

**Comment by geckoslair** [comment]
It's seems closed after @mrocha94 fix :+1:
