### ISSUE TITLE
player known bugs

### ISSUE THREAD

**Issue by mrocha94** [Paratii-Video/paratii-player#88]
Knowns bugs of player page:
- [x] IPFS autoplaying
- [x] Play/Pause button not updating
- [x] Webtorrent not working #90
- [x] Navbar animation isn't working when video is paused
- [x] The left side of the video is being cropped when full screen (only on chrome)
- [x] Unwanted animation when toggling fullscreen

Any other bug, comment it here.

**Comment by felipegaucho** [comment]
- [x] Little purple vertical bar next to the "logout" button on the menu dettaches from the lateral limit of the menu when it expands (moves in a different speed / is not tied togeteher).
- [x] Thumbnail for video Around the Block teaser 16 is missing.
- [x] Cursor shows a **?** icon when hovers over producer's avatar.
- [x] Dark bar below the player w/ controls and progress bar: volume and play icons remain w/ a blue selection box around them after clicked.
