### ISSUE TITLE
error on transaction syncing

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#92]
(node:26158) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): ReferenceError: newTxId is not defined

**Comment by geckoslair** [comment]
Still need to be fixed?

**Comment by jellegerbrandy** [comment]
I think it is fixed, but in any case this code will be refactored on the basis of the nwe contracts (to be deployed)
